### ISSUE TITLE
spam JsonPayload exception

### ISSUE THREAD

**Issue by StalDenc** [ChuckerTeam/chucker#1016]
new JsonPayload exception:Unterminated object at character 78 of {pkg:-,id:1138,tag:"null",channelid:" ",channelname:Chucker ne,isOnGoing:"false",importance:2,isCustomNotification:false,language:ru,style:"android.app.Notification$InboxStyle",isFromPush:"false",isNoClear:false,isForeground:false}
12:33:02.751  8970-9035  HiEve...load  E  new JsonPayload exception:Unterminated object at character 78 of {pkg:-,id:1138,tag:"null",channelid:" ",channelname:Chucker ne,isOnGoing:"false",importance:2,isCustomNotification:false,language:ru,style:"android.app.Notification$InboxStyle",isFromPush:"false",isNoClear:false,isForeground:false}

**Comment by cortinico** [comment]
Please re-open filling the issue template
