### ISSUE TITLE
What is the blocking issues of release 4.0.0?

### ISSUE THREAD

**Issue by trietbui85** [ChuckerTeam/chucker#1029]
First of all, Chucker is really helpful tool for network debugging in Android app. Our team uses it in an app with more than 3M+ installs.

I notice there are 3 non-closed items in the [v4.0.0 milestone](https://github.com/ChuckerTeam/chucker/milestone/11), but it was from 2020. So, are they really necessary to be in v4.0.0? Or is there anything else? [v3.5.2](https://github.com/ChuckerTeam/chucker/releases/tag/3.5.2) is 2 years ago, and I think the v4.0.0 should be released now.

**Comment by cortinico** [comment]
I'm currently waiting on this PR to be merged (cc @4shutosh)
- https://github.com/ChuckerTeam/chucker/pull/988

I was planning to release 4.0.0 last weekend, but this PR came through and I believe it can be included as well.

All the other issues that are linked in 4.0.0 might go into 4.1 or 5.0

**Comment by 4shutosh** [comment]
Yeah, will try to complete & get it merged this week.

**Comment by bazaar-android-interview** [comment]
hi guys 4.0.0 version failed in jitpack:
https://jitpack.io/com/github/ChuckerTeam/chucker/4.0.0/build.log
https://jitpack.io/#ChuckerTeam/chucker
So gradle can not download it as dependency and build fails.

**Comment by DHosseiny** [comment]
hi guys 4.0.0 version failed in jitpack:
https://jitpack.io/com/github/ChuckerTeam/chucker/4.0.0/build.log
https://jitpack.io/#ChuckerTeam/chucker
So gradle can not download it as dependency and build fails.
