### ISSUE TITLE
Chucker doesnt allow saving file of this request

### ISSUE THREAD

**Issue by MadRatSRP** [ChuckerTeam/chucker#1030]
## :writing_hand: Bug description
Request and response body copied from Chucker:
URL: https://example.com/
Method: POST
Protocol: null
Status: Failed
Response: javax.net.ssl.SSLHandshakeException: Unacceptable certificate: CN=GlobalSign Root CA, OU=Root CA, O=GlobalSign nv-sa, C=BE
SSL: Yes
Request time: Tue May 02 20:30:37 GMT+03:00 2023
Response time: null
Duration: null

Request size: 43 B
Response size: null
Total size: 43 B
---------- Request ----------
{
"login": "example" }
---------- Response ----------
(body is empty)

When i press save button on it it says "Failed to save file" (but it still saves an empty file)
With other requests i was able to save file properly, with requests like this one - nope.

## :iphone: Tech info
 - Device: Redmi 9C NFC
 - OS: Android 10
 - Chucker version: 3.5.2

**Comment by cortinico** [comment]
> When i press save button on it it says "Failed to save file" (but it still saves an empty file)
> With other requests i was able to save file properly, with requests like this one - nope.

Can you provide a logcat of what is happening?
Is there anything specific in this request that might cause the failing?

**Comment by OldSoftwareCollection** [comment]
Any thoughts about it?

**Comment by MadRatSRP** [comment]
Any thoughts about it?

**Comment by cortinico** [comment]
> Response size: null

I believe what is happening is that this HTTP response failed to save as it has no body so Chucker can't save it. I'm unsure what are you looking into doing @MadRatSRP, like why do you want to save it?

**Comment by MadRatSRP** [comment]
> > Response size: null
> 
> I believe what is happening is that this HTTP response failed to save as it has no body so Chucker can't save it. I'm unsure what are you looking into doing @MadRatSRP, like why do you want to save it?

This problems happens when our server doesnt have valid SSL sertificate. 

Why do i want to save it as a file - for sharing it from external device where i don't have installed telegram, e.t.c for sharing directly so i would have to create text document, copy text from Chucker and then move the document.

Why doesnt it allow to save it as a file when this error occurs?

**Comment by MadRatSRP** [comment]
I understand now what i was missing - i thought that clicking save button on Response tab allow you to save an entire file, hence why i thought of empty file as a bug.

Could you please add a way to save entire request with responce, e.t.c as a file? By clicking save button. Or to add an option to save a file into explorer when we press "Share as file"?

**Comment by MadRatSRP** [comment]
Also one more thing to add - instead of showing "Failed to save file" message (which for the most users tells about something about permission not granted, e.t.c) when response | request body is empty, please show the exact message, "response is empty" | "response is empty" when trying to save files like these.

This will help most users like myself to understand whats going on faster. It may sound like the obvious thing, but its never like this, you know :D

**Comment by cortinico** [comment]
> Could you please add a way to save entire request with responce, e.t.c as a file? By clicking save button. Or to add an option to save a file into explorer when we press "Share as file"?

That's already possible today with the "Share as file" which allows you to save the whole file.
I've improved the error message here: #1038
