### ISSUE TITLE
Material3 UI Support

### ISSUE THREAD

**Issue by asuka-mio** [ChuckerTeam/chucker#1055]
It will be nice to have a Material3 https://m3.material.io/ inspector UI library

**Comment by cortinico** [comment]
Yes but that's really a low priority request as this is a debugging tool and not a user facing UI

**Comment by rohitjakhar** [comment]
I will happy to implement that.
Please Assign task to me

**Comment by cortinico** [comment]
I think we probably shouldn't do this. Moving to MDC caused situations where the MDC version imported by Chucker was newer than the version from the App, so users would have a different app UI between debug/release. We should have probably used stock android UI views, and not rely on a 3rd party dependency to do graphics, so I don't think we'll be doing Material3 for this library.
