### ISSUE TITLE
Display educationnal text in Http or Error tab when they are empty.

### ISSUE THREAD

**Issue by redwarp** [ChuckerTeam/chucker#106]
**Is your feature request related to a problem? Please describe.**
Currently, when opening the Chucker activity, the HTTP and Error tab are completely blank and empty when there is no request or no error to display.

**Describe the solution you'd like**
Each empty tab is a wasted opportunity to educate users about how to use chucker.
- The Http tab could display something like "This tab displays network requested recorded with the ChuckerInterceptor. Add the interceptor to your OkHttp client to reap the benefits"
- The Error tab could display something like "This tab displays error recorded with the ChuckerCollector.onError method. Call this method when an error is thrown to check your stacktrace live"

Alternative suggestions welcome :-)

**Additional context**
Chucker users will probably know how to use the ChuckerInterceptor: it's well documented, the "Getting Started 👣" section of the README.md describe how to use it. The Error tab is a more hidden feature (one has to read more of the readme :-P and nobody got time for that)

**Do you want to develop this feature yourself?**
[yes]

**Comment by cortinico** [comment]
> Each empty tab is a wasted opportunity to educate users about how to use chucker.

Totally agree here. We could add a couple of lines and deeplink inside an anchor in the README file to show the documentation for every tab/feature.
