### ISSUE TITLE
Build failure due to deleted snapshot version of Chucker library 

### ISSUE THREAD

**Issue by swapnil-patange-hs** [ChuckerTeam/chucker#1061]
## :writing_hand: Describe the bug
We are encountering a build issue related to the Chucker library. It appears that a specific snapshot version of the library (`4.0.0-20230202.073740-219`) has been deleted, leading to the build failure. Here's a summary of the problem:

During the build process, when attempting to resolve the Chucker library, it is found that the specific version (`4.0.0-20230202.073740-219`) we are using has been removed from the repository. As a result, the build fails as the required version is no longer available.

We would appreciate it if the Chucker team could address this issue and provide a solution. It is crucial to either restore the deleted version (`4.0.0-20230202.073740-219`) or provide an alternative solution to ensure the build can proceed successfully.

## :bomb: Steps to reproduce
1. Include the Chucker library in the project.
2. Attempt to build the project, specifying the custom version (`4.0.0-20230202.073740-219`).
3. Observe the build failure due to the unavailability of the specific version in the repository.

## :wrench: Expected behavior
Build should succeed with 4.0.0-20230202.073740-219 version

## :iphone: Tech info
 - Device: 
 - OS: 
 - Chucker version: 

## :page_facing_up: Additional context

**Comment by cortinico** [comment]
> We would appreciate it if the Chucker team could address this issue and provide a solution. It is crucial to either restore the deleted version (`4.0.0-20230202.073740-219`) or provide an alternative solution to ensure the build can proceed successfully.

I'm afraid we can't restore a SNAPSHOT version. Sonatype decides to purge them on a recurrent basis. You should not depend on daily version like this one as a rule of thumb.
I invite you to move to a more recent SNAPSHOT version (and just use `4.0.0-SNAPSHOT`).

**Comment by theapache64** [comment]
@cortinico Regarding 

> ...  to purge them on a recurrent basis ...

Is this something sonatype does automatically and we can't have any control? 🤔

**Comment by cortinico** [comment]
> Is this something sonatype does automatically and we can't have any control? 🤔 If this is happening automatically, what's the period? What do you think about this info in the README, in the `SNAPSHOT` section ?

We don't have any control over them. When you use a `-SNAPSHOT` version, you should expect changes after every commit. Depending on a specific snapshot version is risky exactly because we'll those assets are volatile.

> What do you think about this info in the README, in the SNAPSHOT section ?

Nope we won't be adding a note about it as it's an implementation detail of Sonatype (you can find some information about their schedule here https://issues.sonatype.org/browse/OSSRH-19565).
Users should use a stable version or request one instead of depending on -SNAPSHOT versions.

I know we're late with 4.0.0, I'll be releasing it in the next days.
