### ISSUE TITLE
Grpc integration

### ISSUE THREAD

**Issue by passmanagerapp** [ChuckerTeam/chucker#1097]
## :warning: Is your feature request related to a problem? Please describe
Hi,
Are you planning to integrate this library to GRPC ? https://github.com/grpc/grpc-java/tree/v1.24.0
It would be great if we also use this library while using grpc protocol.

## :raising_hand: Do you want to develop this feature yourself?

- [ ] Yes
- [x] No

**Comment by cortinico** [comment]
Nope we don't have plan to integrate gRPC in the near future as we're heavily dependent on what OkHTTP supports
