### ISSUE TITLE
Project build crashes if there is a smaller version in the project for library "Room"

### ISSUE THREAD

**Issue by danilshik** [ChuckerTeam/chucker#1106]
## :writing_hand: Describe the bug
In projects where Room is used in a smaller version than in Chucker 4.0.0, the project is not going to

## :bomb: Steps to reproduce

1. Use Room in the project version 2.4.2
2. Go from implementation "com.github.chuckerteam.chucker:library:3.5.2" on implementation "com.github.chuckerteam.chucker:library:4.0.0"
3. See error

```
error: onCreate(SupportSQLiteDatabase) in <anonymous 
analytics.app.data.datasources.local.database.ExampleAppDatabase_Impl$1> cannot override onCreate(SupportSQLiteDatabase) in Delegate
      protected void onCreate(SupportSQLiteDatabase _db) {
                     ^
  attempting to assign weaker access privileges; was public
  
  C:\Project\analytics-sdk\app\build\generated\source\kapt\googleDebug\analytics\app\data\datasources\local\database\ExampleAppDatabase_Impl.java:105: error: onValidateSchema(SupportSQLiteDatabase) in <anonymous analytics.app.data.datasources.local.database.ExampleAppDatabase_Impl$1> cannot override onValidateSchema(SupportSQLiteDatabase) in Delegate
      protected RoomOpenHelper.ValidationResult onValidateSchema(SupportSQLiteDatabase _db) {
                                                ^
  attempting to assign weaker access privileges; was public
```

## :wrench: Expected behavior
Successful build

## :iphone: Tech info
 - Device: All
 - OS: All
 - Chucker version: 4.0.0

**Comment by cortinico** [comment]
> In projects where Room is used in a smaller version than in Chucker 4.0.0, the project is not going to

Can you complete this sentence?

**Comment by danilshik** [comment]
my project uses Room v2.4.2.

chucker v4.0.0 uses Room v2.5.2 => conflict versions Room that crashes the project build

**Comment by cortinico** [comment]
I've looked into this and this is caused by a change inside Room so that's outside the scope of this library. You can workaround this change by either:
1. Updating to Room v2.5.2
2. Removing the transitive dependencies on Room in your `build.gradle.kts` file as follows
```
    debugImplementation("com.github.chuckerteam.chucker:library:4.0.0") {
        exclude(group = "androidx.room")
    }
    releaseImplementation("com.github.chuckerteam.chucker:library-no-op:4.0.0") {
        exclude(group = "androidx.room")
    }
```
