### ISSUE TITLE
Optional JSON formatting support

### ISSUE THREAD

**Issue by KevinPosim** [ChuckerTeam/chucker#115]
Pretty sure Chuck did formatted JSON output but Chucker appears to be a compact format sans any white space / line feeds. Makes the output much harder to read.

Would love to have the option to show RESPONSE area pretty printed. Seems maybe it is pretty printed for small payloads and not for larger ones (could be the way our server sends it as well).

**Comment by xbao** [comment]
Is the server returning the 'Content-Type' as 'application/json' (or any string that contains 'json')?

**Comment by cortinico** [comment]
So Chucker won't pretty print your JSON body unless the `Content-Type` header contains `json`.

If your backend is not setting the `Content-Type` properly, the body won't be parsed and will just be returned as it is.

On the other hand, I'm updating the font of the body to use a `monospace` as it will make everything more readable (see #118)

**Comment by zihadrizkyef** [comment]
Hi @cortinico, my backend already setting `Content-Type: application/json`. but Chucker not still not pretty print. What can i do to fix this?

![image](https://user-images.githubusercontent.com/22538348/65416367-d9bf7100-de21-11e9-949a-d851a6272fb1.png)

**Comment by cortinico** [comment]
Is this happening with every request @zihadrizkyef ? Have you tried the Chucker sample app? Is that happing also over there?

**Comment by zihadrizkyef** [comment]
> Is this happening with every request @zihadrizkyef?

Before i was using chuck v2.0.4. After i update the version to v3.0.1, the request is not pretty printed.
It happen in all request.

> Have you tried the Chucker sample app? Is that happing also over there?

No, i dont use the sample

**Comment by shaubert** [comment]
com.chuckerteam.chucker.api.internal.data.entity.HttpTransaction.kt:205

    fun getFormattedResponseBody(): String {
        return responseBody?.let { formatBody(it, requestContentType) } ?: ""
    }

should be responseContentType

**Comment by cortinico** [comment]
@shaubert You're correct. That has already been fixed in #103 and will be shipped in the upcoming release `3.1.0` (that will ideally also fix the pretty printing issue)

**Comment by cortinico** [comment]
@zihadrizkyef In the meanwhile, you can try the latest `develop` snapshots that should contain the fix:

https://github.com/ChuckerTeam/chucker#snapshots-

**Comment by zihadrizkyef** [comment]
Thank you, really love your library :)

**Comment by satyarths** [comment]
Hi there. Just wanted to follow up on the release plan for this. Is there an eta for 3.1.0 ?

**Comment by cortinico** [comment]
> Hi there. Just wanted to follow up on the release plan for this. Is there an eta for 3.1.0 ?

Ideally should be out in a couple of weeks. If you need the latest `develop` branch, you can still use the snapshots

**Comment by Aksi0m** [comment]
Hi! Any new info about the time when the 3.1.0 is supposed to come out?

**Comment by cortinico** [comment]
> Hi! Any new info about the time when the 3.1.0 is supposed to come out?

More info on this in #194 👍
