### ISSUE TITLE
Chucker working fine in react native debug build. how to enable in release build? 

### ISSUE THREAD

**Issue by karthikkarunanithi91** [ChuckerTeam/chucker#1161]
We are using below version

    debugImplementation "com.github.chuckerteam.chucker:library:4.1.0-SNAPSHOT"
    releaseImplementation "com.github.chuckerteam.chucker:library-no-op:4.1.0-SNAPSHOT"

**Comment by cortinico** [comment]
Can you explain better what is your problem?

**Comment by karthikkarunanithi91** [comment]
chucker working fine in debug build. when i change the build command in terminal like (npx react-native run-android --variant release)  the checker is not working
