### ISSUE TITLE
Better RTL support

### ISSUE THREAD

**Issue by eitanaviv** [ChuckerTeam/chucker#117]
**Is your feature request related to a problem? Please describe.**
It would be nicer if Chucker could have a better support for RTL devices.

**Describe the solution you'd like**
ViewPager works the opposite way on RTL layout and some texts are overlapping each other.

**Describe alternatives you've considered**
Better RTL support.

**Additional context**
![Screenshot_1568793405](https://user-images.githubusercontent.com/35567702/65129159-6eca0080-da03-11e9-94c5-56776ccd8739.png)
![Screenshot_1568793426](https://user-images.githubusercontent.com/35567702/65129161-7093c400-da03-11e9-87e9-2944fa251fd8.png)

**Do you want to develop this feature yourself?**
No unfortunately.

**Comment by cortinico** [comment]
Thanks for the report @eitanaviv 

Having full support for RTL will require to update the `ViewPagers` and `TabLayouts` to handle both LTR and RTL.

To fix your situation, I've currently forced all the layouts to be LTR. This will prevent strings from overlapping and will make sure the ViewPagers are working in the right direction.
Once `ViewPager2` will be released and stable, we can consider providing full RTL support.

**Comment by vbuberen** [comment]
Would like to reopen and assign myself to this issue. Going to update my #159 with RTL support, since forcing LTR isn't an option in long-time perspective. Targeting for `3.2.0` for release.

**Comment by vbuberen** [comment]
There are some serious changes to be done in layouts, like `Overview` tab, so decided to make it in a separate branch to not mix with `ViewPager2` code updates.

**Comment by vbuberen** [comment]
Hi @eitanaviv 
Am I right that you use RTL on a daily basis?
If so, I would like to ask you to help me a little bit by providing feedback on my implementation of RTL support.
You can try it out by adding a snapshot as dependency into your app:
`implementation 'com.github.ChuckerTeam:Chucker:feature~rtl_support-SNAPSHOT'`

Also, I would like to ask how the response body in `Response` tab should look like. Should it be mirrored as well?

**Comment by vbuberen** [comment]
Closing this issue, since #208 is already merged. In case any troubles found with updated RTL implementation - open new issues.
