### ISSUE TITLE
Control what to show/ hide in request/ response bodies

### ISSUE THREAD

**Issue by Batsh** [ChuckerTeam/chucker#1181]
In my project there are many requests that contain Base64 which can be a very large string that could cause ANR when trying to see the details of APIs calls.

it would be nice if we can replace large strings with a truncated value like this for example:
`image:[truncated]`

**Comment by cortinico** [comment]
That you can already do today by setting a `.maxContentLength(...)` as suggested here

https://github.com/ChuckerTeam/chucker#configure-

**Comment by Batsh** [comment]
@cortinico this doesn't solve the issue I'm facing.

redactHeaders() works for headers, but there is no method to redact request body or response values that can take much space in the body

**Comment by cortinico** [comment]
> redactHeaders() works for headers, but there is no method to redact request body or response values that can take much space in the body

I mentioned `maxContentLength()`, not `redactHeaders()`
