### ISSUE TITLE
Allow tracking of all network calls

### ISSUE THREAD

**Issue by Batsh** [ChuckerTeam/chucker#1182]
Chucker in iOS can track all network calls such as Firebase and Google APIs, it would be nice to have this feature in Android as well

**Comment by cortinico** [comment]
> Chucker in iOS

Which library are you referring to?

**Comment by Batsh** [comment]
@cortinico sorry not chucker I was referring to this library [netfox](https://github.com/kasketis/netfox).

when using network inspection in Android Studio we can catch **all** network calls, it would be great if we can see it from notifications

**Comment by cortinico** [comment]
The problem is that Chucker works as an OkHTTP interceptor. Android Studio will probably work as a proxy. So this is a technical limitation of this library and we won't be able to implement it easily
