### ISSUE TITLE
chucker/4.0.0 build faild on jitpack

### ISSUE THREAD

**Issue by DHosseiny** [ChuckerTeam/chucker#1190]
Hello, chucker verion 4.0.0 build fails on jitpck. link provided. 
Please provide:

Link to build log from https://jitpack.io/
https://jitpack.io/com/github/ChuckerTeam/chucker/4.0.0/build.log
https://jitpack.io/#ChuckerTeam/chucker

Does the project build on your machine with the same commands (e.g. ./gradlew install) ?
no

What error are you seeing?
Failed to resolve: com.github.ChuckerTeam.Chucker:library:4.0.0

**Comment by cortinico** [comment]
You should be consuming Chucker from Maven Central and not from JitPack as we don't maintain that build

**Comment by DHosseiny** [comment]
So readme file should be updated
