### ISSUE TITLE
Duplicate class com.chuckerteam.chucker.api.Chucker found in modules jetified-library-4.0.0-runtime 

### ISSUE THREAD

**Issue by rizwanspare8** [ChuckerTeam/chucker#1223]
## :writing_hand: Describe the bug

after adding the third party Sdk( phonepe sdk)  in my existing project i am getting this error  while running the code in Android Studio

 See error

## :wrench: Expected behavior
Duplicate class com.chuckerteam.chucker.api.Chucker found in modules jetified-library-4.0.0-runtime (com.github.chuckerteam.chucker:library:4.0.0) and jetified-library-no-op-3.5.2-runtime (com.github.chuckerteam.chucker:library-no-op:3.5.2)
Duplicate class com.chuckerteam.chucker.api.ChuckerCollector found in modules jetified-library-4.0.0-runtime (com.github.chuckerteam.chucker:library:4.0.0) and jetified-library-no-op-3.5.2-runtime (com.github.chuckerteam.chucker:library-no-op:3.5.2)
Duplicate class com.chuckerteam.chucker.api.ChuckerInterceptor found in modules jetified-library-4.0.0-runtime (com.github.chuckerteam.chucker:library:4.0.0) and jetified-library-no-op-3.5.2-runtime (com.github.chuckerteam.chucker:library-no-op:3.5.2)
Duplicate class com.chuckerteam.chucker.api.ChuckerInterceptor$Builder found in modules jetified-library-4.0.0-runtime (com.github.chuckerteam.chucker:library:4.0.0) and jetified-library-no-op-3.5.2-runtime (com.github.chuckerteam.chucker:library-no-op:3.5.2)
Duplicate class com.chuckerteam.chucker.api.RetentionManager found in modules jetified-library-4.0.0-runtime (com.github.chuckerteam.chucker:library:4.0.0) and jetified-library-no-op-3.5.2-runtime (com.github.chuckerteam.chucker:library-no-op:3.5.2)
Duplicate class com.chuckerteam.chucker.api.RetentionManager$Period found in modules jetified-library-4.0.0-runtime (com.github.chuckerteam.chucker:library:4.0.0) and jetified-library-no-op-3.5.2-runtime (com.github.chuckerteam.chucker:library-no-op:3.5.2)

Go to the documentation to learn how to Fix dependency resolution errors.

 - Chucker version:

**Comment by cortinico** [comment]
That's happening because you added Chucker "twice".

> Duplicate class com.chuckerteam.chucker.api.Chucker found in modules jetified-library-4.0.0-runtime (com.github.chuckerteam.chucker:library:4.0.0) and jetified-library-no-op-3.5.2-runtime (com.github.chuckerteam.chucker:library-no-op:3.5.2)

Not sure why without looking at your project.

**Comment by rizwanspare8** [comment]
I have added chuker dependecy single timein my project  , this error comes when i add phonepe (indian payment sdk)sdk

**Comment by ARPIT2208** [comment]
Hi @rizwanspare8 did you get any solution ? i am also facing same issue.

**Comment by rizwanspare8** [comment]
> Hi @rizwanspare8 did you get any solution ? i am also facing same issue.
 you have to exclude chuker dependency from your sdk like this
    implementation(libs.phonepe.sdk) {
        exclude group: 'com.github.chuckerteam.chucker', module: 'library-no-op'
    }
