### ISSUE TITLE
Global Interceptor adding

### ISSUE THREAD

**Issue by SurajValluru** [ChuckerTeam/chucker#1239]
## :warning: Is your feature request related to a problem? Please describe
I have a very huge existing project and I can't refactor my code to add interceptors at each and every client. 

## :bulb: Describe the solution you'd like
I want to add the interceptor at one place that would intercept all the calls without having to refactor code. Maybe there is a way to override the builder? 

## :raising_hand: Do you want to develop this feature yourself?

- [ ] Yes
- [x] No

**Comment by cortinico** [comment]
> Maybe there is a way to override the builder?

I'm not aware of such a way sadly.
