### ISSUE TITLE
Add Support for Android 15 - Toolbar is not accessible on api level 35

### ISSUE THREAD

**Issue by robertdroid** [ChuckerTeam/chucker#1280]
## :writing_hand: Describe the bug
When I open the chucker activity from the notification list is not possible to tap the options in the toolbar, like search, share or go back.

## :bomb: Steps to reproduce
1. Update the targetSdkVersion to 35
2. Run the project
3. make an request
4. Open the request from the notification list.
5. Try to search or share some request.

## :wrench: Expected behavior
Be able to tap the options in the toolbar

## :camera: Screenshots
![image](https://github.com/user-attachments/assets/70f7981b-2ec1-4c24-93d5-8e40130273c4)
![image](https://github.com/user-attachments/assets/46ea2be7-d7d0-4441-bea6-839e794f3295)

## :iphone: Tech info
 - Device: Emulator (Android Studio API level 35)
 - OS: Android 15
 - Chucker version: 3.5.2 and 4.0.0

## :page_facing_up: Additional context
I had the same problem in my app, and this documentation help me to fix it https://developer.android.com/about/versions/15/behavior-changes-15#not-edge-to-edge

**Comment by cortinico** [comment]
Yup we need to add support for Android 15, contribs are more than welcome 🙏

**Comment by robertdroid** [comment]
You are using com.google.android.material, so you only need to add fitsSystemWindows when you use Toolbar.

`
<com.google.android.material.appbar.MaterialToolbar
            [...]
           android:fitsSystemWindows="true" />
`

**Comment by cortinico** [comment]
> You are using com.google.android.material, so you only need to add fitsSystemWindows when you use Toolbar after upload the target version

Please send a PR with the fix and we can merge it 👍

**Comment by markoeltiger** [comment]
@cortinico please close this issue as it is fixed

**Comment by AlexAsRoger** [comment]
When do you plan to release the version with the fix? In the [changelog](https://github.com/ChuckerTeam/chucker/blob/main/CHANGELOG.md) it is part of the Unreleased version 🤔

**Comment by cortinico** [comment]
> When do you plan to release the version with the fix? In the [changelog](https://github.com/ChuckerTeam/chucker/blob/main/CHANGELOG.md?rgh-link-date=2024-11-11T23%3A05%3A02Z) it is part of the Unreleased version 🤔

I'll make one over the coming weeks 👍
