### ISSUE TITLE
Custom Build Variant not working in Kotlin DSL

### ISSUE THREAD

**Issue by erikgunawan** [ChuckerTeam/chucker#1288]
## :writing_hand: Describe the bug

I have 3 build variants: debug, beta, release

Here are the chucker implementations:

```
  debugImplementation "com.github.chuckerteam.chucker:library:3.5.2"
  betaImplementation "com.github.chuckerteam.chucker:library:3.5.2"
  releaseImplementation 'com.github.chuckerteam.chucker:library-no-op:3.5.2'
```

And then I tried to migrate the build configuration from Groovy to Kotlin DSL, so I changed the implementations to these:

  ```
debugImplementation(libs.chucker)
  betaImplementation(libs.chucker)
  releaseImplementation(libs.chucker.no.op)
```

After that, when building the apps, I got this warning:

  ```
Unresolved reference: betaImplementation
  ```

I have tried some options, but none of them work

1.
 ` 
add("beta", libs.chucker)
`

2.
`
"betaImplementation"(libs.chucker)
`

**Comment by cortinico** [comment]
> "betaImplementation"(libs.chucker)

This is the correct syntax for Kotlin DSL and should work.

**Comment by erikgunawan** [comment]
> > "betaImplementation"(libs.chucker)
> 
> This is the correct syntax for Kotlin DSL and should work.

It doesn't work, Chucker notification doesn't appear.

**Comment by cortinico** [comment]
> It doesn't work, Chucker notification doesn't appear.

Then please provide a reproducer using this template:
https://github.com/cortinico/kotlin-android-template

and I'll look into it

**Comment by erikgunawan** [comment]
> > "betaImplementation"(libs.chucker)
> 
> This is the correct syntax for Kotlin DSL and should work.

Aah my bad, after checking deeply, the issue is because I'm using multi-module architecture (data, domain, app modules). 

I call Chucker with the `Debug` checker like this:

```
if (BuildConfig.DEBUG) {
      okBuilder.addInterceptor(
        Builder(context)
          .collector(ChuckerCollector(context))
          .maxContentLength(250000L)
          .redactHeaders(emptySet())
          .alwaysReadResponseBody(true)
          .build()
      )
    }
```

In the data modules, BuildConfig.DEBUG is always returned false, so the chucker doesn't show. After removing that logic, it works well.

Thanks @cortinico
