### ISSUE TITLE
Copy Response Feature

### ISSUE THREAD

**Issue by A7ak** [ChuckerTeam/chucker#1299]
## :warning: Is your feature request related to a problem? Please describe

There is no way to copy the response 

## :bulb: Describe the solution you'd like

Added a copy button in UI to copy the response

## :page_facing_up: Additional context

![Screenshot_1728988025](https://github.com/user-attachments/assets/282f84d3-b1d5-4dd5-b001-bf05f67333e6)
![Screenshot_1728988040](https://github.com/user-attachments/assets/23b3ba18-2d0e-4ce9-8f03-a1e2cd83da5d)

## :raising_hand: Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

**Comment by cortinico** [comment]
> Added a copy button in UI to copy the response

Yup this sounds like a reasonable addition 👍 @A7ak feel free to send over a PR for this one

**Comment by A7ak** [comment]
@cortinico  please review this [Implemented copy feature](https://github.com/ChuckerTeam/chucker/pull/1300)

**Comment by A7ak** [comment]
@cortinico  fixed linting issue 
https://github.com/ChuckerTeam/chucker/pull/1300/commits/ad96f4d9417caa22f9f12bab555152db662b2489

**Comment by cortinico** [comment]
> @cortinico fixed linting issue [ad96f4d](https://github.com/ChuckerTeam/chucker/commit/ad96f4d9417caa22f9f12bab555152db662b2489)

Yup thanks for that. I will review it next week 👍

**Comment by A7ak** [comment]
@cortinico  requested changes are done when free please it

**Comment by cortinico** [comment]
> @cortinico requested changes are done when free please review it #1300

Sure thing! I've left a couple of minor comments + We need to test it on dark mode. After that, we should be good to go
