### ISSUE TITLE
Kotlin compiler incompatibility issues

### ISSUE THREAD

**Issue by madlymad** [ChuckerTeam/chucker#1320]
## :writing_hand: Describe the bug

Kotlin upgrade to 2.1.0 is making any Kotlin project with 1.9 to fail. #1317
This is because Kotlin compiler 1.9 is compatible with 2.0.x only.
So any project that is forced to use 4.1.0-SNAPSHOT due to missing fixes on 4.0.0 is now facing build issues.

A possible temporary workaround is to use `4.1.0-20241129.105208-78` instead of `4.1.0-SNAPSHOT` version but with this approach after some days (a month or so) the snapshot is removed from the system as a result this approach is very unreliable, and can only used as temporary workaround.

## :bomb: Steps to reproduce

1. Use any android project with Kotlin 1.9
2. Use 4.1.0-SNAPSHOT version
3. Build the project
4. Project fail to build due to incompatible Kotlin versions

## :wrench: Expected behavior

The project would be able to build.
A suggestion to fix the issue is to provide an official release (4.1.0 or 4.0.1) that will contain all the changes of the last working commit d40710040fceea3882f5bc1872371d02dbe4f176 before the introduction of the breaking Kotlin change.

## :camera: Screenshots

![Screenshot 2024-12-03 at 1 31 12 PM](https://github.com/user-attachments/assets/27c47c2b-57d7-475a-8c9b-c5e943a3939c)

## :iphone: Tech info
 - Chucker version: develop 3e078d4022a5313167dc24288a91a203f0218dbf

## :page_facing_up: Additional context

To make matters worse https://jitpack.io/#ChuckerTeam/chucker/Tag is no longer working so you cannot produce a missing version.
There is no official release since Jul 1, 2023

Thank you in advance 😃

**Comment by cortinico** [comment]
> To make matters worse [jitpack.io#ChuckerTeam/chucker/Tag](https://jitpack.io/#ChuckerTeam/chucker/Tag) is no longer working so you cannot produce a missing version. There is no official release since Jul 1, 2023
> 
> Thank you in advance 😃

Thank you for the heads up.
Yup I'll do a Chucker release without the Kotlin 2.1 bump so you'll be able to use it.
It will be out in the coming weeks, sorry for the delay

**Comment by cortinico** [comment]
I'm waiting for:
- https://github.com/ChuckerTeam/chucker/pull/1300

to land and I'll do the release work afterwards

**Comment by cortinico** [comment]
Just released https://github.com/ChuckerTeam/chucker/releases/tag/4.1.0 which should unblock you
