### ISSUE TITLE
Configure notification priority

### ISSUE THREAD

**Issue by vibin** [ChuckerTeam/chucker#154]
Hi, I would love to have a way to set Chuck's notification priority to NotificationCompat.PRIORITY_MIN (https://stackoverflow.com/a/16999675) so that Android can hide it from the status bar (it gets pretty annoying otherwise, for someone using a debug app all day :)).

Let me know if this sounds good. I can take a shot at this, this weekend.

**Comment by vbuberen** [comment]
Why don't you just set priority for Chuck right on a device?

I believe that your use case is quite rare and device settings should be enough to handle it.
Chucker is a debug tool after all, so it is Ok to get notifications :)

**Comment by vibin** [comment]
Notification priority set by user gets cleared whenever app is reinstalled - which can be very common in debug apps to change environment, etc. 

> Chucker is a debug tool after all, so it is Ok to get notifications

My issue is just about the status bar icon, not the notification itself :)

**Comment by vibin** [comment]
@cortinico what do you think? Notification channels are immutable once created, so it's impossible to do this in the client code.

**Comment by cortinico** [comment]
> @cortinico what do you think? Notification channels are immutable once created, so it's impossible to do this in the client code.

Hi @vibin 
Thanks for raising the issue and apologize for the extremely late reply.

To answer your question: you can re-define a Notification Channel using the same Channel ID set by Chucker (that is `chucker`):

https://github.com/ChuckerTeam/chucker/blob/012e6582872a211dcffd98fd59603495c1cf7666/library/src/main/java/com/chuckerteam/chucker/internal/support/NotificationHelper.kt#L21

This will override the priority originally set by Chucker. 
Just call `createNotificationChannel` in your client in a way like this:

```kotlin
(context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager).createNotificationChannel(
                NotificationChannel(
                        "chucker",
                        "Overridden Chucker Channel",
                        NotificationManager.IMPORTANCE_MIN
                )
        )
```

**Comment by vibin** [comment]
I didn't realise I could redefine the notification channel - will try that. Thanks a lot, @cortinico!
