### ISSUE TITLE
URL Encoder/Decoder

### ISSUE THREAD

**Issue by sulemankhants** [ChuckerTeam/chucker#155]
Please do provide url encode and decode for api request

**Comment by cortinico** [comment]
@sulemankhants Can I ask you to be a bit more specific and provide some example? Are you interested in seeing a decoded version of the URL in the Chucker interface? If yes, where exactly? Do you have some use case/scenarios?

**Comment by vbuberen** [comment]
@sulemankhants 
Am I correct that you suggest to add functionality to be able to switch how the url is displayed (encoded/decoded) like this?
<img width="556" alt="Screenshot 2020-01-16 at 11 26 44" src="https://user-images.githubusercontent.com/13467769/72511104-391f1200-3853-11ea-8c1e-e092ab51724d.png">

**Comment by sulemankhants** [comment]
yes Volodymyr Buberenko you are correct

**Comment by vbuberen** [comment]
Yeah, good idea. Thanks.

**Comment by sulemankhants** [comment]
Please also add json formatter in chucker

**Comment by vbuberen** [comment]
@sulemankhants I would kindly ask you to open a new issue with feature request about JSON formatting, so maintainers won't miss it and other users could see and take part in discussions.

**Comment by cortinico** [comment]
Any reason why the pendingpr bot removed the `feature request` label here 🧐

**Comment by vbuberen** [comment]
I think it just removes all the label here. Strange.
