### ISSUE TITLE
request/response time formatting

### ISSUE THREAD

**Issue by scruffyfox** [ChuckerTeam/chucker#158]
The request time and response time in the overview tab is not being properly formatted

### :wrench: Expected behaviour

Previous functionality as expected from Chuck

![Screenshot 2019-11-15 at 13 51 12](https://user-images.githubusercontent.com/1050665/68948224-5120d980-07af-11ea-9b06-ac9bb6551c1d.png)
![Screenshot 2019-11-15 at 13 52 26](https://user-images.githubusercontent.com/1050665/68948225-5120d980-07af-11ea-93fb-ce83940bfb5c.png)

**Comment by vbuberen** [comment]
Good catch @scruffyfox. Interesting that no other active Chucker users, including me, noticed this issue 😄

**Comment by cortinico** [comment]
Thanks for reporting @scruffyfox The fix is now merged and will be shipped with the next release
