### ISSUE TITLE
[Feedback] Chucker usage with Ktor HTTP client

### ISSUE THREAD

**Issue by psh** [ChuckerTeam/chucker#177]
I spent some time learning about the [Ktor HTTP client](https://ktor.io/clients/index.html) recently, porting the `HttpBinClient` and `HttpBinApi` to the Ktor HTTP client as a learning exercise for myself.  

In the process I was happy to find that Chucker works perfectly with the Ktor HTTP client when configured to use the `OkHttp` engine - 
```kotlin
private val httpClient = HttpClient(OkHttp) {
    install(JsonFeature) {
        serializer = GsonSerializer()
    }
    engine {
        addInterceptor(chuckerInterceptor)
        addInterceptor(HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY))
        config {
            followRedirects(true)
            readTimeout(30, TimeUnit.SECONDS)
            connectTimeout(30, TimeUnit.SECONDS)
            callTimeout(30, TimeUnit.SECONDS)
        }
    }
}
```
👍  Great work all!

**Comment by cortinico** [comment]
Awesome! Thanks for sharing this @psh!

**Comment by GuilhE** [comment]
Just to add my 2 cents, I've configured my `HttpClient` throughout `expect/actual` logic in a **KMM** project and _Chucker_ runs happily on **androidApp** 😃
