### ISSUE TITLE
Replace publishing plugin

### ISSUE THREAD

**Issue by vbuberen** [ChuckerTeam/chucker#178]
## :warning: Is your feature request related to a problem? Please describe.
The plugin, which currently used for publishing along with POM generation is officially abandoned, according to https://github.com/dcendents/android-maven-gradle-plugin

## :dart: Describe the solution you'd like
In order to avoid possible problems with compatibility in future Chucker should migrate to some alternative, like https://github.com/sky-uk/gradle-maven-plugin which is suggested by the author of deprecated plugin.

**Comment by technoir42** [comment]
Starting with Android Gradle plugin 3.6 you can publish Android libraries without any third-party 
plugins https://developer.android.com/studio/preview/features#maven-publish (NOTE: this link will be dead once AGP 3.6 goes stable).

**Comment by cortinico** [comment]
> Starting with Android Gradle plugin 3.6 you can publish Android libraries without any third-party plugins

@vbuberen should we give it a try?

**Comment by vbuberen** [comment]
Sure, I would love to try. Just let's wait for stable and hope that it won't be like `ViewBinding` - claiming that it is null-safe, while actually not.
An example of null-non-safety in `ViewBinding`
https://issuetracker.google.com/issues/147792710

**Comment by cortinico** [comment]
Well, publishing plugins sounds like an easier task than null-safety 😅

**Comment by vbuberen** [comment]
Updated link to for stable `3.6.0`:
https://developer.android.com/studio/build/maven-publish-plugin
