### ISSUE TITLE
Internal classes are visible to outsiders

### ISSUE THREAD

**Issue by vbuberen** [ChuckerTeam/chucker#179]
## :loudspeaker: Describe the bug
Internal Chucker classes are visible for apps using this library.

### :wrench: Expected behavior
Internal implementation shouldn't be visible in projects with Chucker added as dependency.

## :camera: Screenshots
Screenshots from real project, which uses Chucker for debugging purposes
<img width="480" alt="Screen Shot 2020-01-06 at 15 45 28" src="https://user-images.githubusercontent.com/13467769/71822376-5d356300-309d-11ea-9f9c-3c2bcf853a07.png">
<img width="508" alt="Screen Shot 2020-01-06 at 15 46 38" src="https://user-images.githubusercontent.com/13467769/71822377-5d356300-309d-11ea-916c-d75bfd43fff4.png">

**Comment by cortinico** [comment]
Yup that's actually a bug. Whatever is inside the `.internal` package should have the `internal` modifier.

**Comment by vbuberen** [comment]
Closing as #180 was just merged.
