### ISSUE TITLE
Payload size isn't correct for some transactions

### ISSUE THREAD

**Issue by vbuberen** [ChuckerTeam/chucker#209]
## :loudspeaker: Describe the bug
Some transactions show payload size as `-1`. It is totally fine, since OkHttp returns this value in case the size is unknown. However, when I wanted to handle this value in Chucker UI I decided to check what other network interceptors show and found out that [Stetho](https://facebook.github.io/stetho/) show sizes for transactions, which show `-1` in Chucker.

### :wrench: Expected behavior
Transactions show actual size instead of `-1`.

## :camera: Screenshots
<img width="920" alt="Screen Shot 2020-01-26 at 10 51 39" src="https://user-images.githubusercontent.com/13467769/73132894-f830b580-4029-11ea-96bd-c0c06151244e.png">

**Comment by vbuberen** [comment]
After some basic investigation found out that Chucker solely relies on `contentLength` value in response to show the size, while Stetho does some calculations itself in case response headers have no `contentLength` value. Requests from the screenshot in my bug report are exactly such items with no mentioned value in their response.

So Chucker needs to implement the same mechanism.

**Comment by MiSikora** [comment]
This could be fixed after merging #267. We would have to keep counting the bytes in `TeeSource` and report it back in the callback.

**Comment by MiSikora** [comment]
I was thinking about this feature lately and see couple of things that could be done.

* If `Content-Length` is available Chucker could just use this value to determine the size of the response.
* If `Content-Length` is not available Chucker could wait for the response to be read in a `TeeSource` and be informed about bytes read once upstream is depleted. The problem occurs if the consumer does not read bytes fully like reported in #287. In this case there is no way of knowing what would be the size of the response.
* Chucker could display amount of data that was downloaded by the user and the size of the response if it is available (either form `Content-Length` or from `TeeSource` if exhausted). It would require some UI changes on most of the screens.
* Chucker could show gradual changes of downloaded data. So while bytes are being read from an upstream it would display `8 kB`, `16 kB`, `24 kB` and so on. Not really sure if there is a need for this. Also it would require UI changes mentioned in the previous point.

**Comment by vbuberen** [comment]
Moving further, so we could release `3.2.0`

@MiSikora as to your ideas - agree on first 3 points, but the last one with progressive update of the request size is an overengineering, which won't bring much value to our users.

**Comment by MiSikora** [comment]
Yes, I think so as well. Just wanted to propose it in case you find it valuable.

**Comment by cortinico** [comment]
Agree on the first 3 points as well. On a side note I was also wondering if we should show the `Content-Length` aside the size. 

I actually think it might be valuable for the user to see `Content-Leght: -1` next to `Size: xxx B` to realise that the `Content-Leght` was missing.

**Comment by vbuberen** [comment]
We could show `Unknown` instead of `-1` to be more specific or just drop the line with `Content-Lenght` at all from transaction description in such cases.

**Comment by cortinico** [comment]
> We could show `Unknown` instead of `-1` to be more specific 

++

**Comment by aldoKelvianto** [comment]
Hi, I would like to bump this issue because it still occurs on my project.

I've been using `3.1.2` and `3.2.0` release. It still produces incorrect `content-size`, while Chuck shows the correct `content-size`.

**Chucker**
![Screenshot_1586144808](https://user-images.githubusercontent.com/5099600/78522071-49151500-77f6-11ea-9db0-99429fd07bfa.png)


**Chuck**
![Screenshot_1586145396](https://user-images.githubusercontent.com/5099600/78522073-4b776f00-77f6-11ea-9f4c-b5ec875ee777.png)

**Comment by vbuberen** [comment]
Hi @aldoKelvianto 
Thanks for reporting. The fix for this issue wasn't deployed yet, so there is nothing to bump :)

However, it is strange that Chuck shows the size while Chucker not.
Are these transactions have no `Content-Length` header?

**Comment by cortinico** [comment]
Thanks for reporting @aldoKelvianto 

> It still produces incorrect content-size, while Chuck shows the correct content-size.

Can you please share the `.addInterceptor(...)` configuration you're using? Are you applying both Chuck and Chucker together? Do you have other interceptors? If yes, what's the order?

**Comment by aldoKelvianto** [comment]
> However, it is strange that Chuck shows the size while Chucker not.
Are these transactions have no Content-Length header?

You guess it correctly. There's no `Content-Length` header in the API response. In Chucker's sample App, the responses contain `content-length`.

![Screenshot_1586331382 copy](https://user-images.githubusercontent.com/5099600/78758352-317d8e00-79a8-11ea-99dc-1d84cd6e9640.png)

![Screenshot_1586331376 copy](https://user-images.githubusercontent.com/5099600/78758338-2b87ad00-79a8-11ea-9f69-0856c240688b.png)

However, in my project, the response doesn't have `content-length`
![Screenshot_1586345143 copy](https://user-images.githubusercontent.com/5099600/78779119-9811a480-79c6-11ea-9042-fc31e5c676c2.png)

> However, it is strange that Chuck shows the size while Chucker not.

Yes, this surprises me as well 😄

**Comment by aldoKelvianto** [comment]
> Thanks for reporting @aldoKelvianto
> It still produces incorrect content-size, while Chuck shows the correct content-size.
Can you please share the .addInterceptor(...) configuration you're using? Are you applying both Chuck and Chucker together? Do you have other interceptors? If yes, what's the order?

You're welcome!

Sure, however, I don't think you'll find it interesting.

```kotlin

private fun createOkHttpClient(): OkHttpClient =
    OkHttpClient.Builder().apply {
        cache(createOkHttpCache())
        addInterceptor(ChuckerInterceptor(context))
        connectTimeout(CONNECT_TIMEOUT, TimeUnit.SECONDS)
        readTimeout(READ_TIMEOUT, TimeUnit.SECONDS)
    }.build()
```

I don't use other interceptors. I replace `ChuckInterceptor` with `ChuckerInterceptor`.

**Comment by cortinico** [comment]
> You guess it correctly. There's no `Content-Length` header in the API response.

Great. As discussed above we're probably going to decouple the `Content-Length` to the actual payload size in two different fields.
