### ISSUE TITLE
In memory DB version of Chucker

### ISSUE THREAD

**Issue by pellyadolfo** [ChuckerTeam/chucker#213]
## :warning: Is your feature request related to a problem? Please describe.
I do not want to install RDBMS as SQLite in my app as it is 3+MB, even for debug flavour

## :dart: Describe the solution you'd like
I would like to have an in memory DB version of chucker so i do not need to install Room, SQLite and related RDBMS projects.

## :bar_chart: Describe alternatives you've considered
The idea comes from https://github.com/Ashok-Varma/Gander

## :pencil: Do you want to develop this feature yourself?
- [ ] Yes
- [X] No

**Comment by vbuberen** [comment]
Hi @pellyadolfo 
Thanks for your idea, but I don't think that it is worth it to spend time providing such functionality. 
Room + SQLite takes not that much space. Here is a screenshot from APK Analyzer of Chucker sample app:
<img width="1228" alt="Screenshot 2020-01-28 at 16 06 37" src="https://user-images.githubusercontent.com/13467769/73270932-61f6be00-41e8-11ea-9dc8-01804a976851.png">

As you can see it is ~70 KB, so `profit/time invested` makes this feature disadvantageousю

**Comment by pellyadolfo** [comment]
ok, thanks
