### ISSUE TITLE
No method found for ViewModel

### ISSUE THREAD

**Issue by Nekromancer** [ChuckerTeam/chucker#217]
## :loudspeaker: Describe the bug
Screen from Firebase crash report. This only occurs with `minifyEnabled true`. Is there some config missing in pro-guard setup?

![image](https://user-images.githubusercontent.com/3933348/73430736-14409980-433f-11ea-8f4a-1386501cb839.png)

## :bomb: To Reproduce
I got this crash report from UAT environment and i cannot reach author to find out reproduction path. I'm pretty sure that this happens when http request fails.

### :wrench: Expected behavior
It should not crash

## :iphone: Smartphone
 - Device: Galaxy Note10
 - OS: Android 10
 - Lib version: 3.1.1

**Comment by vbuberen** [comment]
Thanks for your report.
It seems that we have issues with custom `TransactionViewModelFactory()` in our code.
I am going to handle it.

**Comment by vbuberen** [comment]
Closing due to #219 being merged.
