### ISSUE TITLE
Question - Other HTTP input sources?

### ISSUE THREAD

**Issue by psh** [ChuckerTeam/chucker#224]
Probably a deeply philosophical question, but, in your opinion is Chucker

* A log of HTTP traffic that *utilizes* an OkHTTP interceptor to do its work

or

* An OkHTTP interceptor that lets you *visualize* the traffic that it's seen

The reason I ask is whether there's an interest in being able to collect HTTP traffic (clearly the *live beating heart of Chucker* and the core of its mission) from other HTTP clients, specifically the Ktor client, and investigating others too?

Is there an interest in broadening the data collection part of the project, or is OkHttp itself the core of the mission?  If there's an interest in expanding the reach of the tool, how would you see the architecture evolving to accommodate them?

**Comment by cortinico** [comment]
IMHO The latter:

> An OkHTTP interceptor that lets you visualize the traffic that it's seen

On the other hand I'm more than happy to hear from the community what's the point of view on this. I'm up for extending the support of Chucker to other HTTP clients but only if there is a real demand for this.

Such work would require a significant amount of time to extract and abstract a lot of the logic from the `ChuckerInterceptor` out to an abstraction layer, that we currently don't have.

**Comment by vbuberen** [comment]
I believe that we shouldn't restrict ourselves to only OkHttp. 
But also agree with @cortinico that we should add more clients if there is a demand for such move.
