### ISSUE TITLE
Chucker corrupts image resources.

### ISSUE THREAD

**Issue by MiSikora** [ChuckerTeam/chucker#225]
## :loudspeaker: Describe the bug
If `OkHttp` client with the `ChuckerInterceptor` is used for image downloads then the requests fail.

## :bomb: To Reproduce
1. Run the sample project. - https://github.com/MiSikora/Chucker-Bug
2. Run the app.
3. Select the check box to enable Chucker.
4. Press either `Coil` or `Picasso` buttons.

### :wrench: Expected behavior
The image should be downloaded and displayed in the ImageView. It should work in the same way as if the `ChuckerInterceptor` was disabled.

## :camera: Screenshots
Stack trace for `Picasso`.

```
java.io.IOException: Failed to decode stream.
  at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:161)
  at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:229)
  at com.squareup.picasso.RequestCreator.get(RequestCreator.java:429)
  at io.mehow.demo.MainActivity$onCreate$3$1.invoke(MainActivity.kt:54)
  at io.mehow.demo.MainActivity$onCreate$3$1.invoke(MainActivity.kt:23)
  at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

Stack trace for `Coil`.

```
java.lang.IllegalStateException: BitmapFactory returned a null Bitmap. Often this means BitmapFactory could not decode the image data read from the input source (e.g. network or disk) as it's not encoded as a valid image format.
  at coil.decode.BitmapFactoryDecoder.decode(BitmapFactoryDecoder.kt:156)
  at coil.RealImageLoader$loadData$2.invokeSuspend(RealImageLoader.kt:392)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

## :iphone: Smartphone
 - Device: Any Device
 - OS: Any OS
 - Lib version: `3.1.1`

## :page_facing_up: Additional context
Issue does not exist in `3.1.0`. It was introduced with `3.1.1`.

**Comment by vbuberen** [comment]
Hi @MiSikora 
Thanks for your report and for the sample, but, please, next time provide samples without preview features, like `view binding`, since, for example, I don't have 3.6 RC02, but only 3.5.3 and 4.0 canary 9, both of which don't know what `view binding` is.

**Comment by MiSikora** [comment]
Hi @vbuberen 
Android Studio Canary 9 has `ViewBinding`. You need to enable it in a different way. 

```groovy
android {
  buildFeatures {
    viewBinding = true
  }
}
```

Or via Gradle properties.

https://developer.android.com/studio/preview/features#buildfeatures

**Comment by vbuberen** [comment]
Thanks for pointing out. Didn't know that :)
Debugging the problem now and see that there is an issue with response processing.
Here is how response content looks like before reaching `processReponse()`
<img width="405" alt="Before processing" src="https://user-images.githubusercontent.com/13467769/73687728-55d09c00-46d3-11ea-944a-33592d737ec1.png">
And here is after:
<img width="387" alt="After" src="https://user-images.githubusercontent.com/13467769/73687752-6123c780-46d3-11ea-93e2-fc3784acdd43.png">
Going to try my solution of creating copy for processing and returning original response further the chain. I wanted to use it in 3.1.1, but another solution from @cortinico was ready and worked better at that moment.

**Comment by MiSikora** [comment]
Cool, thanks for the quick response.

If copying is a to go solution maybe you could try to play around tee command - https://github.com/square/okio/issues/186

I don't know if that's helpful. I might give it a stab when I find some time.

**Comment by cortinico** [comment]
Thanks for reporting and thanks for providing also a reproducible environemtn @MiSikora. 

> Going to try my solution of creating copy for processing and returning original response further the chain.

Let me know if you do any progress on this side @vbuberen 

> I don't know if that's helpful. I might give it a stab when I find some time.

If you happen to have time for this, we would really appreciate your contribution :)
