### ISSUE TITLE
Add more info about TLS connection in transaction overview

### ISSUE THREAD

**Issue by vbuberen** [ChuckerTeam/chucker#236]
## :warning: Is your feature request related to a problem? Please describe
Currently Chucker shows only `Yes` or `No` in SSL field of transaction overview. We could show more info, like TLS protocol version, cipher suites and even some certificates info.

## :bulb: Describe the solution you'd like
At initial stage I would love to see TLS version and cipher suite in `Overview` tab. 

## :raising_hand: Do you want to develop this feature yourself?
- [x] Yes
- [ ] No

**Comment by cortinico** [comment]
Sounds great to me!
