### ISSUE TITLE
Transaction data is updated constantly.

### ISSUE THREAD

**Issue by vbuberen** [ChuckerTeam/chucker#244]
## :writing_hand: Describe the bug
When user stays on some opened transaction and an app continues network activity in the background the whole transaction data on all 3 transaction tabs updates on each new transaction.
As a result, not only Chucker does redundant work, but also some flashing happens.

## :bomb: Steps to reproduce

1. Open any transaction details while app continues firing new requests in the background.
2. Observe screen flashing on each new transaction.

## :wrench: Expected behavior
Transaction (I guess the same thing happens with `Throwable`) is retrieved and filled only once when user on any of transaction details tabs.

## :camera: Screenshots
Cropped the gif due to privacy reasons:
![chucker_live_data_issue_cropped](https://user-images.githubusercontent.com/13467769/74670802-94c21f80-51b2-11ea-8b86-e06e2dacaf3d.gif)

## :iphone: Tech info
 - Chucker version: 3.1.2

**Comment by vbuberen** [comment]
Would like to deal with it, but too overwhelmed at the moment. Assume that will have time in ~2 weeks.
If someone would like to pick it up in the meanwhile, please let me know here.

**Comment by MiSikora** [comment]
@vbuberen I'll fix it.

**Comment by vbuberen** [comment]
Thank you. I will check your PR with encode stuff today in the evening.

**Comment by MiSikora** [comment]
No worries. Take your time if you need it. :)
