### ISSUE TITLE
Add pre-commit hooks to run code checks

### ISSUE THREAD

**Issue by vbuberen** [ChuckerTeam/chucker#248]
## :warning: Is your feature request related to a problem? Please describe
It seems that contributors often have to do multiple commits, since their contributions have issues with styling etc.

## :bulb: Describe the solution you'd like
It might be more convenient to run `ktlintCheck` and `detekt` tasks as a pre-commit hook. With these changes contributors could be sure that their code passes Chucker checks and also make our library build process a little more eco-friendly, since we won't have to spin up Travis CI that often 🌲

## :page_facing_up: Additional context
We might also include `test` step as well.

## :raising_hand: Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

**Comment by cortinico** [comment]
++ for pre-commit hooks. Are you planning to use some tool to distribute them @vbuberen or how do we architect this?

**Comment by vbuberen** [comment]
I wanted to do something simple to not introduce any additional tool. 
Something like [standard hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) should work fine.

**Comment by cortinico** [comment]
> I wanted to do something simple to not introduce any additional tool.
> Something like [standard hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) should work fine.

Yes my point was more that hooks are not part of the git repo (they're not applied when the repo is cloned). So we need some sort of tools to install them on the first build or similar.

**Comment by ColtonIdle** [comment]
ktlint-gradle might be able to help

https://github.com/jlleitschuh/ktlint-gradle

> addKtlintFormatGitPreCommitHook

I think they recommended (overheard in kotlinglang slack) adding that to the clean task in your gradle project so that it gets added to everyones machine.

**Comment by vbuberen** [comment]
Thanks for sharing. Looks interesting.

**Comment by cortinico** [comment]
I'm adding a note for this in the README 👍

**Comment by vbuberen** [comment]
I am currently playing around with pre-commit hook, which is installed from `clean` task as suggested, which runs both `detekt` and `ktlintCheck` commands. Let's install it automatically, since I don't hope that people will actually read these recomendations.

**Comment by vbuberen** [comment]
Closed by #408
