### ISSUE TITLE
Add state for empty screens

### ISSUE THREAD

**Issue by vbuberen** [ChuckerTeam/chucker#276]
## :warning: Is your feature request related to a problem? Please describe
Currently Chucker shows no difference between a request with empty body and a request which somehow failed to fetch info to display. States should be distinct, so user could understand what is going on.

## :bulb: Describe the solution you'd like
In cases where the request/response is really empty we should show some state telling user that there is an empty request/response. 

## :page_facing_up: Additional context
Here is how empty state looks now
![Screenshot 2020-03-17 at 22 00 16](https://user-images.githubusercontent.com/13467769/76896806-33699b00-689b-11ea-9812-1b3b0cefda0b.png)

## :raising_hand: Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

**Comment by cortinico** [comment]
Totally agree. Ideally having some graphic would be helpful. Maybe some Vector Drawable to do not impact on the library size. Otherwise just text would work fine.

**Comment by vbuberen** [comment]
Yes, I thought about drawable as well. Actually, I already picked one. Here is an example
<img width="379" alt="Screenshot 2020-03-18 at 13 53 26" src="https://user-images.githubusercontent.com/13467769/76958177-eda2e600-691f-11ea-85d8-18d96e17d9ed.png">
I will change the text in future, just tries to see how it looks. I selected such emoticon with neutral face, because empty payload isn't something bad. It is just a `neutral state` 😄 

The problem with implementation of such state is in fact that with the current logic in TransactionPayloadFragment's AsyncTask we are transaction items into a `TransactionPayloadItem` and, thus, by the time we need to change visibility of items we already have just items with strings and can't clearly define if there is an empty request or response. So we need to update this logic. But, since we already have #270 opened I would prefer to merge it first and do updates there to not do the job twice. Also, it seems that the idea shared in #259 about splitting `Request` and `Response` into its own entities might be a good helper here as well.

**Comment by cortinico** [comment]
> Yes, I thought about drawable as well. Actually, I already picked one. Here is an example

I'd go for something more positive if possible (like this https://materialdesignicons.com/icon/package-variant).

I personally considered the _neutral face_ to inform that something hasn't really worked as expected but that's no big deal (like a failure that is not preventing the app from working). Also please note that the majority of the HTTP requests (GETs) are without request body, so that icon will be shown a lot of times.

But that's just my personal taste.

Agree to let #270 and #259 go over this (this is a nice to have imho).

**Comment by vbuberen** [comment]
Your option is great actually. Overlooked an empty package icon when tried to pick something for this purpose.
