### ISSUE TITLE
Question: Is there feature similar for logs, using Log.d and see it?

### ISSUE THREAD

**Issue by emilianocds** [ChuckerTeam/chucker#284]
## :warning: Is your feature request related to a problem? Please describe

No, just a question regarding this library and I'm looking something similar but for log cat.
## :raising_hand: Do you want to develop this feature yourself?

- [ ] Yes
- [x] No

**Comment by cortinico** [comment]
Hi @emilianocds 
You can probably use the OkHTTP's `HttpLoggingInterceptor` to achieve a similar result. You'll be able to see your network requests on LogCat.

More details here: https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor
