### ISSUE TITLE
App crash when using com.google.android.material library

### ISSUE THREAD

**Issue by kriskast** [ChuckerTeam/chucker#292]
When project uses the library: com.google.android.material, the app crashes after adding the chucker to gradle. Looks like chucker is also using the same library

`android.view.InflateException: Binary XML file line #127: Binary XML file line #127: Error inflating class com.google.android.material.textfield.TextInputLayout`

**Comment by vbuberen** [comment]
Hi there. Thanks for reporting this issue. 
However, if you want to get help with your issue faster I would appreciate if you not just drop the whole template, but fill out all the info you have.

There is nothing wrong with Chucker using Material components library. A lot of users, including me use both libraries in their projects without any issues. Share additional info like version of Material you trying to use, that mentioned `TextInputLayout`.

**Comment by kriskast** [comment]
Sure thing, is there a way we can exude Chucker from using the material library and instead use the project supplied one? I am using this material library:

` api 'com.google.android.material:material:1.1.0'`

## :bomb: Steps to reproduce

1. Add the google material library and use the `TextInputLayout` view
2. Add Chucker to gradle
3. Run app and crash

## :wrench: Expected behavior
Shouldn't crash

![image](https://user-images.githubusercontent.com/12373559/77665350-d26b5280-6f7f-11ea-9ce6-f809d806b927.png)

**Comment by vbuberen** [comment]
What is the motivation behind using `api` instead of `implementation` in your project?

**Comment by kriskast** [comment]
I was looking for a fix, but it has the same issue when switched to `implementation 'com.google.android.material:material:1.1.0'`

**Comment by vbuberen** [comment]
Please show me your TextInputLayout in xml as I requested in my first reply.

**Comment by kriskast** [comment]
`<com.google.android.material.textfield.TextInputLayout
                    android:id="@+id/til_email"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="25dp"
                    android:baselineAligned="false"
                    style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
                    app:hintTextAppearance="@style/TextInputLayoutNormal"
                    app:errorTextAppearance="@style/TextInputLayoutError"
                    app:boxStrokeWidth="1dp"
                    app:boxStrokeColor="@color/colorGreyLight"
                    android:textColorHint="@color/colorGreyLight"
                    app:hintEnabled="true"
                    app:passwordToggleEnabled="true">`

**Comment by vbuberen** [comment]
Hmm, don't see any clashing ids, etc. Strange.
I have 3 active projects using Chucker and Material without issues.

**Comment by MiSikora** [comment]
> Sure thing, is there a way we can exude Chucker from using the material library and instead use the project supplied one? I am using this material library:

You can force the dependency version with something like this.

```groovy
allprojects {
  configurations.all {
    resolutionStrategy {
      eachDependency { details ->
        def requested = details.requested
        if (requested.group == "com.google.android.material" && requested.name == "material") {
          details.useVersion "1.1.0"
        }
      }
    }
  }
}
```

However, I'm also not facing the issue you describe in any of my projects that use Chucker. Can you create a small sample repo that reproduces the issue?

**Comment by kriskast** [comment]
Looks like issue was a `ThemeEnforcement ` error. In the project the AppCompat theme is being used instead of the Material Components theme. After adding Chucker the app would crash, adding the below to the theme fixes the crash (but breaks the UI), will hold off the library for now as it not that important.

https://material.io/develop/android/docs/getting-started/

`
  <item name="colorPrimaryVariant">@color/my_app_primary_variant_color</item>
  <item name="colorSecondaryVariant">@color/my_app_secondary_variant_color</item>
  <item name="colorSurface">@color/my_app_surface_color</item>
  <item name="colorOnPrimary">@color/my_app_color_on_primary</item>
  <item name="colorOnSecondary">@color/my_app_color_on_secondary</item>
  <item name="colorOnBackground">@color/my_app_color_on_background</item>
  <item name="colorOnError">@color/my_app_color_on_error</item>
  <item name="colorOnSurface">@color/my_app_color_on_surface</item>
  <item name="scrimBackground">@color/mtrl_scrim_color</item>
  <item name="textAppearanceHeadline1">@style/TextAppearance.MaterialComponents.Headline1</item>
  <item name="textAppearanceHeadline2">@style/TextAppearance.MaterialComponents.Headline2</item>
  <item name="textAppearanceHeadline3">@style/TextAppearance.MaterialComponents.Headline3</item>
  <item name="textAppearanceHeadline4">@style/TextAppearance.MaterialComponents.Headline4</item>
  <item name="textAppearanceHeadline5">@style/TextAppearance.MaterialComponents.Headline5</item>
  <item name="textAppearanceHeadline6">@style/TextAppearance.MaterialComponents.Headline6</item>
  <item name="textAppearanceSubtitle1">@style/TextAppearance.MaterialComponents.Subtitle1</item>
  <item name="textAppearanceSubtitle2">@style/TextAppearance.MaterialComponents.Subtitle2</item>
  <item name="textAppearanceBody1">@style/TextAppearance.MaterialComponents.Body1</item>
  <item name="textAppearanceBody2">@style/TextAppearance.MaterialComponents.Body2</item>
  <item name="textAppearanceCaption">@style/TextAppearance.MaterialComponents.Caption</item>
  <item name="textAppearanceButton">@style/TextAppearance.MaterialComponents.Button</item>
  <item name="textAppearanceOverline">@style/TextAppearance.MaterialComponents.Overline</item>`

**Comment by vbuberen** [comment]
I would like to reopen the issue till we find the actual fix. It is strange, since quite a lot of people still use AppCompat theme with Chucker without issues.

You mentioned that your app uses `AppCompat`. If so could you tell me how is it possible that your `TextInputLayout` uses `style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"`, while it requires `Theme.MaterialComponents` to be used and would crash otherwise with an error like you have?
