### ISSUE TITLE
Update to androidx?

### ISSUE THREAD

**Issue by psh** [ChuckerTeam/chucker#30]
I notice that you have an 'updated-deps' branch out there, and there's a general move toward modernizing the codebase with Kotlin.  How do you feel about moving over to using Android Jetpack `androidx` for AppCompatActivity, Fragments, etc?  

**Do you want to develop this feature yourself?**
Happy to, yes.

**Comment by ZakTaccardi** [comment]
See #62

**Comment by cortinico** [comment]
Hey @uOOOO 
Would you be able to send out a PR with AndroidX support?

**Comment by uOOOO** [comment]
Sure, I made the PR.

**Comment by cortinico** [comment]
Closed by #89
