### ISSUE TITLE
Long query parameters in request list

### ISSUE THREAD

**Issue by Dkhusainov** [ChuckerTeam/chucker#310]
## :warning: Is your feature request related to a problem? Please describe
Our Android app sends request with token both in header and query params(so GET request could be copied from log without curl for example). This causes Chucker request view in "Network" tab to take half the size of the list.

## :bulb: Describe the solution you'd like
Either:
1. Interceptor to format data before displaying it in the list
2. Interceptor to modify request/response data befory saving it to db

## :raising_hand: Do you want to develop this feature yourself?
- [x] Yes
- [ ] No

**Comment by vbuberen** [comment]
Thanks for reporting and using Chucker!

I think we can apply a much simpler solution and just limit max lines in list items on this tab. Users could see the full item by opening it anyway.

4 lines should be enough, I believe.
