### ISSUE TITLE
Closeable resource not closed

### ISSUE THREAD

**Issue by Dkhusainov** [ChuckerTeam/chucker#311]
## :writing_hand: Describe the bug
Debug build with `StrictMode detectLeakedClosableObjects` reports leaked resource at
`com.chuckerteam.chucker.api.ChuckerInterceptor$ChuckerTransactionTeeCallback.readResponseBuffer(ChuckerInterceptor.kt:253)`

## :bomb: Steps to reproduce

1. add `StrictMode.setVmPolicy(StrictMode.VmPolicy.Builder().detectAll().penaltyLog().build())`
2. make test requests

## :iphone: Tech info
 - Chucker version: 3.2.0

**Comment by vbuberen** [comment]
Thanks for reporting this issue.
Good catch!

**Comment by vbuberen** [comment]
@MiSikora Should I leave it for you as for original feature creator?

**Comment by MiSikora** [comment]
Sure, I'll take a look and fix it when I find some time this week.
