### ISSUE TITLE
Detect contrast colour for downloaded images

### ISSUE THREAD

**Issue by MiSikora** [ChuckerTeam/chucker#319]
## :warning: Is your feature request related to a problem? Please describe

Downloading images that are fully tinted with a colour in a range of the background colour used by Chucker makes them virtually invisible for the user. Here is an example of such an icon which is white. It is visible in night mode but not in day mode.

## :bulb: Describe the solution you'd like

Use `Palette` to determine what should be a contrasting background for the image. It could look like something along the lines of this.

https://github.com/MiSikora/Squash-It/blob/93812d1a13d8fbb62c2290659d0785f250f94507/squash-it/library/src/main/java/io/mehow/squashit/screenshot/ScreenshotActivity.kt#L55-L60

The only difference would be to use `Palette` output to get colour instead of day or night mode.

## :page_facing_up: Additional context

![Screenshot_20200407-172130](https://user-images.githubusercontent.com/30936061/78688024-156ce480-78f5-11ea-8f19-266eefb8549f.jpg)

![Screenshot_20200407-172209](https://user-images.githubusercontent.com/30936061/78688090-2cabd200-78f5-11ea-88a8-a937e6bfdf7f.jpg)

## :raising_hand: Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

**Comment by vbuberen** [comment]
Great catch
