### ISSUE TITLE
java.lang.IllegalStateException  You can't access the throwable repository if you don't initialize it!

### ISSUE THREAD

**Issue by gaoliangchao** [ChuckerTeam/chucker#364]
![image](https://user-images.githubusercontent.com/16502015/84234355-af841f80-ab26-11ea-8bbf-de2e58103806.png)
Always find the occasional crash.

**Comment by gaoliangchao** [comment]
![image](https://user-images.githubusercontent.com/16502015/84241438-0fcc8e80-ab32-11ea-8889-3aa5ed1eef69.png)

**Comment by cortinico** [comment]
Hi @gaoliangchao

Please updated your issue using the Bug Report template that is provided by the repo. We can't help you in this manner, specifically:

- You're not saying on which version of Chucker this is happening
- The stacktrace is a screenshoot, therefore is not selectable nor searchable for users that could have a similar issue.

**Comment by gaoliangchao** [comment]
Hi @cortinico ,

Update the using version info and Bug Report:
Gradle implementation com.github.ChuckerTeam.Chucker:library:3.2.0

java.lang.RuntimeException:Unable to start activity ComponentInfo{com.homecredit.hccn.customerapp/com.chuckerteam.chucker.internal.ui.MainActivity}: java.lang.IllegalStateException: You can't access the throwable repository if you don't initialize it!
-- android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3760)
 ......
 java.lang.IllegalStateException:You can't access the throwable repository if you don't initialize it!
 com.chuckerteam.chucker.internal.data.repository.RepositoryProvider.com.chuckerteam.chucker.internal.data.repository.RecordedThrowableRepository throwable()(RepositoryProvider.kt:1)
 com.chuckerteam.chucker.internal.ui.MainViewModel.void <init>()(MainViewModel.kt:5)
 java.lang.Class.newInstance(Native Method)
 androidx.lifecycle.ViewModelProvider$NewInstanceFactory.androidx.lifecycle.ViewModel create(java.lang.Class)(ViewModelProvider.java:1)
 androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.androidx.lifecycle.ViewModel create(java.lang.Class)(ViewModelProvider.java:7)
 androidx.lifecycle.SavedStateViewModelFactory.androidx.lifecycle.ViewModel create(java.lang.String,java.lang.Class)(SavedStateViewModelFactory.java:4)
 androidx.lifecycle.ViewModelProvider.androidx.lifecycle.ViewModel get(java.lang.String,java.lang.Class)(ViewModelProvider.java:9)
 androidx.lifecycle.ViewModelProvider.androidx.lifecycle.ViewModel get(java.lang.Class)(ViewModelProvider.java:2)
 com.vdog.VLibrary.v1(Native Method)
 com.chuckerteam.chucker.internal.ui.transaction.TransactionListFragment.onCreate(Unknown Source:23)
 androidx.fragment.app.Fragment.void performCreate(android.os.Bundle)(Fragment.java:5)
 androidx.fragment.app.FragmentStateManager.void create()(FragmentStateManager.java:5)
 androidx.fragment.app.FragmentManager.void moveToState(androidx.fragment.app.Fragment,int)(FragmentManager.java:23)
 androidx.fragment.app.FragmentManager.void moveToState(androidx.fragment.app.Fragment)(FragmentManager.java:69)
 androidx.fragment.app.FragmentManager.void moveFragmentToExpectedState(androidx.fragment.app.Fragment)(FragmentManager.java:4)
 androidx.fragment.app.FragmentManager.void moveToState(int,boolean)(FragmentManager.java:75)
 androidx.fragment.app.FragmentManager.void dispatchStateChange(int)(FragmentManager.java:3)
 androidx.fragment.app.FragmentManager.void dispatchCreate()(FragmentManager.java:3)
 androidx.fragment.app.FragmentController.void dispatchCreate()(FragmentController.java:1)
 com.vdog.VLibrary.v1(Native Method)
 androidx.fragment.app.FragmentActivity.onCreate(Unknown Source:23)
 com.vdog.VLibrary.v1(Native Method)
 androidx.appcompat.app.AppCompatActivity.onCreate(Unknown Source:23)
 com.vdog.VLibrary.v1(Native Method)
 com.chuckerteam.chucker.internal.ui.BaseChuckerActivity.onCreate(Unknown Source:23)
 com.vdog.VLibrary.v1(Native Method)
 com.chuckerteam.chucker.internal.ui.MainActivity.onCreate(Unknown Source:23)
 android.app.Activity.performCreate(Activity.java:8066)
 android.app.Activity.performCreate(Activity.java:8054)
 android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3733)
 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3939)
 android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
 android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
 android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2373)
 android.os.Handler.dispatchMessage(Handler.java:107)
 android.os.Looper.loop(Looper.java:213)
 android.app.ActivityThread.main(ActivityThread.java:8147)
 java.lang.reflect.Method.invoke(Native Method)
 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by vbuberen** [comment]
Thanks for your report. 
I have seen such issue 1 or 2 times only when we just introduced `ViewModel` to the codebase, but it was a few months ago, but wasn't able to reproduce it back when as well as don't know how do it now.
Another case with similar exception of repository being not initialised was a `Clear` action from the notification, but I did a fix for it quite a long time ago, so it was release somewhere in `3.1.0`.

Would really appreciate if someone could share his experience and if someone knows the pattern to reproduce the issue.

**Comment by gaoliangchao** [comment]
@cortinico @vbuberen ,
So sorry, I wasn't able to reproduce this issue too. We just added an interceptor to OKhttp in our code.
Our tester sometimes come across this crash, which occurred 18 times in the last week.

**Comment by MiSikora** [comment]
It is associated with process death. To reproduce you can do the following.

1. Open the sample app.
2. Collect test requests.
3. Open Chucker Activity.
4. Open some request details.
5. Hide the app.
6. Kill the process.
7. Open the app. It will crash with the reported stack trace.

Below you can find a gif.

![sample](https://user-images.githubusercontent.com/30936061/85203560-ee785900-b30e-11ea-9fbe-c76e1deeaacc.gif)

**Comment by MiSikora** [comment]
Quick and dirty solution is to wrap all instances of access to the repositories with `lazy` and change the initialisation order in `TransactionActivity` to something like this.

```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
    val transactionId = intent.getLongExtra(EXTRA_TRANSACTION_ID, 0)
    viewModel = ViewModelProvider(this, TransactionViewModelFactory(transactionId))
        .get(TransactionViewModel::class.java)
    super.onCreate(savedInstanceState)

    // Rest of the code…
```

Otherwise on recreation from the process death fragments are initialised during the `onCreate` of the the activity. I don't know the proper solution from the top of my head since I don't usually work with fragments or AAC but most likely proper DI should help here.
