### ISSUE TITLE
Shared text is empty if don't keep is enabled

### ISSUE THREAD

**Issue by koral--** [ChuckerTeam/chucker#367]
## :writing_hand: Describe the bug
Issue occurs along with #366 so environment and repro steps are the same.
Not sure if fix for #366 will also fix this so creating this issue FTR.

In such case target activity receives empty text.

## :bomb: Steps to reproduce

1. Go to any request
2. Click on share as curl, but may be anything probably

## :wrench: Expected behavior
There is no crash and  target activity receives proper text.

## :iphone: Tech info
 - Device: OnePlus 7
 - OS: 10
 - Chucker version: 3.2.0
## :page_facing_up: Additional context
Enable don't keep activities to reproduce it easier

**Comment by vbuberen** [comment]
Hey there. Thanks for reporting.

I would appreciate if you fill this issue following our template as we require from all reporters/contributors.

Talking about this issue - I will try to address it, but could you tell me if you have ever seen the behavior such flag creates somewhere in real life?

**Comment by koral--** [comment]
OK, I've edited the first post to match the template.

Regarding the behavior in real life, I've seen it. Eg. on low-end devices after starting camera activity for ACTION_IMAGE_CAPTURE. Many times the caller app process gets killed.

**Comment by vbuberen** [comment]
Thanks for editing and for sharing how to get such behavior in real life.
