### ISSUE TITLE
URL does not show port number

### ISSUE THREAD

**Issue by ColtonIdle** [ChuckerTeam/chucker#403]
## :writing_hand: Describe the bug
If a URL includes a port number, it should be shown as part of the url, just like charles proxy

**Comment by cortinico** [comment]
Yup, that's right. We should store the `.port()` from the `HttpUrl` here: 
https://github.com/ChuckerTeam/chucker/blob/638e3b9a81735c50f8bc1255ce6cc5aea826e306/library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransaction.kt#L216-L223

**Comment by JayNewstrom** [comment]
Looks like this should be pretty straightforward. #252 seems like the most recent addition that did something pretty similar. Has someone already picked this up, or should I take it?

**Comment by cortinico** [comment]
> or should I take it?

Feel free to work on it 🙏
