### ISSUE TITLE
Support for React Native Application 

### ISSUE THREAD

**Issue by blikenoother** [ChuckerTeam/chucker#412]
## :raising_hand: Do you want to develop this feature yourself?

- [ ] Yes
- [ ] No

**Comment by vbuberen** [comment]
I would kindly ask you to provide info a way that is suggested by feature request template.

**Comment by vbuberen** [comment]
Closing as stale and with lack of required information.

**Comment by YashKumarVerma** [comment]
This feature would be very helpful seeing the lack of any similar implementaiton in the react-native ecosystem

**Comment by cortinico** [comment]
> This feature would be very helpful seeing the lack of any similar implementaiton in the react-native ecosystem

There is nothing preventing you from using Chucker in a React Native application. Obviously the library will work only for Android Apps as the library relies on OkHTTP which is Android only.

**Comment by takeruadelbert** [comment]
is there any update or similar alternative for react native?

**Comment by cortinico** [comment]
> is there any update or similar alternative for react native?

Nope there are no updates. Your best bet of React Native applications is to use Flipper: https://fbflipper.com/

**Comment by LunatiqueCoder** [comment]
Hello @cortinico 

This looks looks amazing. I would love to use this in a React Native application only for Android, but I didn't figure out how to make it work. I have no Android experience at all :/

**Comment by puguhsudarma** [comment]
Hey guys, you can try this library chucker expo wrapper.

https://www.npmjs.com/package/expo-chucker

**Comment by gowravl** [comment]
You can follow this article for Bare React Native App
https://medium.com/@gowrav01/react-native-network-logging-in-android-chucker-6c03cac029c9

**Comment by rezaarifian** [comment]
> You can follow this article for Bare React Native App https://medium.com/@gowrav01/react-native-network-logging-in-android-chucker-6c03cac029c9

I have followed steps on this article.
i got failed build when release variant, on debug mode build successfully.
`28: error: package com.chuckerteam.chucker.api does not exist`

RN: 0.70.9
Chucker: 4.0.0

**Comment by Wellapos** [comment]
@rezaarifian 

I had the same issue. I just paste this in MainApplication.java:

```
import com.chuckerteam.chucker.api.ChuckerInterceptor
import com.facebook.react.modules.network.NetworkingModule
```

and worked!
