### ISSUE TITLE
minor design issue

### ISSUE THREAD

**Issue by okanaydin** [ChuckerTeam/chucker#416]
## :writing_hand: Describe the bug
There is a minor design issue in **chucker_fragment_transaction_overview.xml** where is **responseSizeLabel**.

## :bomb: Steps to reproduce
1. Go to 'Network'
2. Click on 'POST' (or choose one of the requests)
3. See error

## :wrench: Expected behavior
It would be great if the title label should be a single line.

## :camera: Screenshots
![image](https://user-images.githubusercontent.com/11614563/89652062-9355f200-d8cd-11ea-9800-e5755dcffc85.png)

## :iphone: Tech info
 - Device:Oppo Reno 3
 - OS: Android 10 
 - Chucker version: v3.2.0

**Comment by vbuberen** [comment]
Thanks for reporting. 
We already fixed this issue in #313, so in 3.3.0-SNAPSHOT you should proper nice layout 😄
