### ISSUE TITLE
Allow to read the whole response body irrespective of the consumer

### ISSUE THREAD

**Issue by MiSikora** [ChuckerTeam/chucker#432]
## :warning: Is your feature request related to a problem? Please describe

In the light of the discussion on Slack there is a reasonable demand to read the response body even if a client did not wish to consume it or failed to consume it. This is also kind of a legacy from Chuck that is expected to be preserved.

https://kotlinlang.slack.com/archives/CRWD6370R/p1597269092105200
https://kotlinlang.slack.com/archives/CRWD6370R/p1597812748114900

## :bulb: Describe the solution you'd like

I'd like to introduce a new flag for Chucker configuration that would read the whole response body regardless of the underlying work of external libraries like Retrofit or JSON converters. Conceptually it might look like this. If the `alwaysReadResponseBody` flag is set to `true` then upon creating the upstream `TeeSource` would be wrapped around the `DepletingSource`. This might also help with #425.

```kotlin
internal class DepletingSource(delegate: Source) : ForwardingSource(delegate) {
  override fun close() {
    try {
      Okio.buffer(delegate()).readAll(Okio.blackhole())
    } catch (_: IOException) {

    }
    super.close()
  }
}
```

## :bar_chart: Describe alternatives you've considered

I don't see any feasible alternatives. One way would be to read the whole body before passing it to a client but this was the cause of OOM issues and #263 in the past. Turning on the flag would bring back #263. For that reason, I believe, it should default to `false`.

## :raising_hand: Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

**Comment by ColtonIdle** [comment]
@MiSikora thank you. This is awesome. Good to be able to have the "same behavior" as chuck and charles.
