### ISSUE TITLE
Add useragent header to requests

### ISSUE THREAD

**Issue by markchristopherng** [ChuckerTeam/chucker#433]
## :warning: Is your feature request related to a problem? Please describe

Hi, we are using a bot protection tool where we need to test with changing the useragent to activate captchas. Our app uses OkHttp which sets a user agent such as okhttp/3.1.4 (where the number indicates the version of the library.

Currently you don't display the useragent in requests so we can't easily verify if we are setting the user useragent correctly or not. At the moment we have to use another tool called Charles which is more difficult to use than Chuck but displays this information.

## :bulb: Describe the solution you'd like
Show the useragent on the Request

## :bar_chart: Describe alternatives you've considered
Using another tool called Charles to the information

## :page_facing_up: Additional context
None

## :raising_hand: Do you want to develop this feature yourself?

- [ ] Yes
- [ x] No

**Comment by MiSikora** [comment]
If you apply `ChuckerInterceptor` as a network interceptor you'll see `User-Agent` header and all headers that are applied by `OkHttp`.

![Screenshot_1597877076](https://user-images.githubusercontent.com/30936061/90697367-88f90800-e27e-11ea-80d5-694f163fb8ae.png)

**Comment by markchristopherng** [comment]
![Screenshot_20200820-092757](https://user-images.githubusercontent.com/5202898/90700176-786d7f80-e2c8-11ea-8873-e3f0f11b428a.png)
Hi,
We have added the interceptor, however we only see the custom headers that we have added ourselves.

**Comment by markchristopherng** [comment]
We are using V3.2.0

**Comment by MiSikora** [comment]
You are applying it as an application interceptor. You need to do it as a network interceptor. https://square.github.io/okhttp/interceptors/

**Comment by markchristopherng** [comment]
thanks for info, all good now
