### ISSUE TITLE
about installation

### ISSUE THREAD

**Issue by bilgilendirme** [ChuckerTeam/chucker#439]
I want you to view explanatory information about the installation. with screenshots.

**Comment by bilgilendirme** [comment]
Where exactly we need to install these files. I want this very much, but I don't know much about these issues.

**Comment by cortinico** [comment]
You can find installation instructions in the Getting Started section of the README:
https://github.com/ChuckerTeam/chucker#getting-started-

If you get stuck somewhere, please open another issue with your code and we will try to support you.
