### ISSUE TITLE
Unify test naming convention

### ISSUE THREAD

**Issue by MiSikora** [ChuckerTeam/chucker#442]
## :warning: Is your feature request related to a problem? Please describe

Currently, test naming is all over the place. Some tests are scenario-driven, some are technical descriptions of the code, some are in the first person, and so on. This makes it a little bit hard to know how tests should be structured when adding new ones.

https://github.com/ChuckerTeam/chucker/blob/4171d1790d74b88d4efdd697dfa4655a36f5d203/library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt#L54-L56

https://github.com/ChuckerTeam/chucker/blob/4171d1790d74b88d4efdd697dfa4655a36f5d203/library/src/test/java/com/chuckerteam/chucker/internal/data/entity/HttpTransactionTupleTest.kt#L45-L46

https://github.com/ChuckerTeam/chucker/blob/4171d1790d74b88d4efdd697dfa4655a36f5d203/library/src/test/java/com/chuckerteam/chucker/internal/data/entity/HttpTransactionTupleTest.kt#L50-L51

https://github.com/ChuckerTeam/chucker/blob/4171d1790d74b88d4efdd697dfa4655a36f5d203/library/src/test/java/com/chuckerteam/chucker/internal/support/JsonConverterTest.kt#L8-L9

https://github.com/ChuckerTeam/chucker/blob/4171d1790d74b88d4efdd697dfa4655a36f5d203/library/src/test/java/com/chuckerteam/chucker/internal/support/OkHttpUtilsTest.kt#L46-L47

https://github.com/ChuckerTeam/chucker/blob/4171d1790d74b88d4efdd697dfa4655a36f5d203/library/src/test/java/com/chuckerteam/chucker/internal/support/FormatUtilsTest.kt#L14-L15

## :bulb: Describe the solution you'd like

I'd like to have a unified test naming convention so it is easier to read and digest. I would propose scenario-driven test names. I'd even like to go one step further and change tests to the following convention. In my experience, it makes it more obvious and easier to come up with a good name instead of slapping the first or second thing that comes to mind. 

```kotlin
@ParameterizedTest 
@EnumSource(value = ClientFactory::class) 
fun `image responses are available to Chucker`(factory: ClientFactory)

@Test
fun `formatted duration is not available if the duration is unknown`()

@Test
fun `duration is properly formatted`()

@Test
fun `JSON converter is a singleton`()

@Test
fun `response is not considered to be gzipped with a different compression header`()

@Test
fun `JSON with null values is properly formatted`()
```

## :bar_chart: Describe alternatives you've considered

An alternative would be to use a different naming convention. I'm open to discussion and suggestions. In any case, I'd like it to be unified.

## :raising_hand: Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

**Comment by cortinico** [comment]
> An alternative would be to use a different naming convention. I'm open to discussion and suggestions. In any case, I'd like it to be unified.

Thanks for raising this.

I generally go with:

```kotlin
@Test
fun <methodUndertest>_with<Preconditions>_<expectedOutcome>() {...} 
```

I never really used backticks-named tests, but I'm open to go for that actually.
The only concern I have on that front, it generally makes function names longer and it could clash with static analysis tools (for example: https://github.com/detekt/detekt/issues/2745).

Happy to hear what others' opinions are

**Comment by MiSikora** [comment]
Yeah, issues with static analysis can be PITA. On the other having too long test names would suggest that they should be most likely shortened.

For me, the biggest advantage of plain English test names is that developers are not constrained by anything and don't have to create contrived names like `givenNoRequestDuration_whenFormattedDurationIsRetrieved_thenItIsNotAvailable`. They just have to write a sentence in English.

```kotlin
@Test
fun <methodUndertest>_with<Preconditions>_<expectedOutcome>() {...} 
```

Using this format is ok but I don't like one thing about it. It contains a method under test, which should not matter for most of the cases. It is useful when writing a library with an API that will be consumed like i.e. `okio`, `vavr` or `arrow-kt`. But even then there are more complex behaviour tests which are more about setup or calling more methods in a particular order. They can fall short here and it might be hard to fit them to this format.

**Comment by cortinico** [comment]
> It contains a method under test, which should not matter for most of the cases

As a rule of them that is the name of the method for Unit tests on the public and internal API (e.g. if you have an internal Util class, you will still write tests for each of the method).

For behavioural/UI tests I generally replace the first section with the "scenario" under tests.

However given that we have to audit all the tests, I think it's worth to give the backticks approach a shoot

**Comment by vbuberen** [comment]
I am in for backticks approach as well. Haven't used it before, but as I see them in other repos it looks and feels good.
