### ISSUE TITLE
Failed to resolve: com.github.chuckerteam.chucker:library:2.0.4

### ISSUE THREAD

**Issue by su1216** [ChuckerTeam/chucker#45]
**Describe the bug**
Failed to resolve: com.github.chuckerteam.chucker:library:2.0.4

2.0.3 is ok

**Comment by cortinico** [comment]
Thanks for the report @su1216

I've just pushed a git tag for 2.0.4
Can I ask you to check if the bug is solved now?

**Comment by cortinico** [comment]
I tested this yesterday and I can confirm that it works.
Moreover please note that the Maven Coordinates are case sensitive so you should use:

`com.github.ChuckerTeam.Chucker:library:2.0.4`
