### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by mertceyhan** [ChuckerTeam/chucker#468]
## :warning: Is your feature request related to a problem? Please describe
Sometimes reading the content on the checker can be hard with the light screen. The dark theme can be a useful feature for reading the content.

## :bulb: Describe the solution you'd like
The dark theme can add to the project.

## :raising_hand: Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

**Comment by cortinico** [comment]
I believe this was already implemented in #143 
Are you experiencing some problems with the current implementation?

**Comment by mertceyhan** [comment]
On my device (Samsung A50) default theme is dark but I still see it with as light. Plus, the settings page can be added for changing themes without device settings.

**Comment by mertceyhan** [comment]
I'll review it and come back

**Comment by vbuberen** [comment]
It was me who implemented dark theme a year ago. I also have a Samsung device with One UI and Chucker is dark for me when system theme is dark.

As to settings page - currently we have no such page, so adding it just for switching the theme will be an overkill from my point of view.

**Comment by mertceyhan** [comment]
@vbuberen You're right. It's working on the device, it's my wrong. Thanks for your comments

**Comment by vbuberen** [comment]
Thanks for using Chucker. 
Looking forward for more feedback 😉
