### ISSUE TITLE
Sometimes response size -1 B on chucker 3.1.2

### ISSUE THREAD

**Issue by sundetova** [ChuckerTeam/chucker#478]
## :writing_hand: Describe the bug
Hello, I updated chucker from 3.0.1 to 3.1.2, and now sometimes I get response size -1 B, but on response tab I receive all data
## :bomb: Steps to reproduce
1. Add chucker as applicationInterceptor
2. okHttp version 3.12.10

## :wrench: Expected behavior
In previous version everything worked fine, I didn't receive -1 B size response
I expect that this version will work fine as well.
## :camera: Screenshots
![Screenshot_20201019-094527_2](https://user-images.githubusercontent.com/15002085/96399793-072b4980-11f1-11eb-9d95-f9dee359413a.png)

## :iphone: Tech info
 - Device: Any device
 - OS: Android 8
 - Chucker version: 3.1.2

**Comment by vbuberen** [comment]
Thanks for reporting.

There were issues with payload size in older versions on Chucker since size was taken from headers only. With release of `3.3.0` we introduced a better approach by calculating amount of bytes read ourselves.

I would suggest you to update to the latest version `3.3.0`, since compared to `3.1.2` there are no breaking changes.

**Comment by sundetova** [comment]
> Thanks for reporting.
> 
> There were issues with payload size in older versions on Chucker since size was taken from headers only. With release of `3.3.0` we introduced a better approach by calculating amount of bytes read ourselves.
> 
> I would suggest you to update to the latest version `3.3.0`, since compared to `3.1.2` there are no breaking changes.

Thank you for response. I actually tried to update to `3.2.0`, but again, in response size was -1 B and response tab in UI was empty. Is it bug?

**Comment by vbuberen** [comment]
As I mentioned in the previous message we introduced calculation in `3.3.0` only, not in `3.2.0`. Please give it a try and let me know if it works with the latest update.

**Comment by sundetova** [comment]
Thank you, it works
