### ISSUE TITLE
(encoded or binary body omitted) in Request and Response

### ISSUE THREAD

**Issue by mapm14** [ChuckerTeam/chucker#5]
I have changed from Chuck to Chucker using the steps in the README but now in the Request and Response I get this message instead of the JSON: (encoded or binary body omitted).

I'm using this version of OkHttp: 3.8.1

**Comment by olivierperez** [comment]
This issue has been fixed on the `master` branch. We will release a 2.0.2 in less than a week.

**Comment by mapm14** [comment]
That's great! 😃 Thank you, guys. A really awesome job with this fork.

**Comment by olivierperez** [comment]
Version 2.0.2 is release. Let us know if you still face issues ;-) Have fun!

**Comment by mapm14** [comment]
Great guys, is solved 👍🏻. But changing from Chuck to Chucker, makes the app crash, you need to clear the data of the app, there is a problem with the database:

`Caused by: android.database.sqlite.SQLiteException: no such table: RecordedThrowable (code 1 SQLITE_ERROR): , while compiling: SELECT _id, tag, clazz, message, date FROM 'RecordedThrowable' ORDER BY date DESC`

But I'm not sure if this is considered as a bug (maybe yes, because usually people will upgrade from Chuck). Regardless, thank you so much.

**Comment by cortinico** [comment]
Yeah this should be considered a bug as we probably use a different DB than Chuck

**Comment by olivierperez** [comment]
@mapm14 The crash when updating the database while migrating from Chuck to Chucker is **fixed and released** in [2.0.3](https://github.com/ChuckerTeam/chucker/releases/tag/2.0.3)
