### ISSUE TITLE
When I include the chcucker 3.4.0 in my project ,I faced issuse of image loading

### ISSUE THREAD

**Issue by jitendratiwari** [ChuckerTeam/chucker#513]
When i include 3.4.0 version,In my app I face issuse of loading images,Images are not getting loaded.
Pls let me know if u need more details

**Comment by cortinico** [comment]
Yup, we need more details:
- Can you fill the issue template from the repository
- Can you give more details on what "Images are not getting loaded."
- Which image loading library are you using
- Are you using the OkHTTP client where you apply chucker also for image loading
- Can you post a gif/video of the bug

**Comment by MiSikora** [comment]
I am closing as there is no follow-up. Feel free to reopen if there is more information.
