### ISSUE TITLE
Chucker is unable to show key-value of an Authorization request header

### ISSUE THREAD

**Issue by mochadwi** [ChuckerTeam/chucker#531]
## :writing_hand: Describe the bug

Since **_Okhttp_** detecting a different base url (requesting a 2 different network services in one activity/fragment)

1. for `ServiceA` **_Chucker_** able to show the request header (`Authorization: Bearer dummytokenloremipsum`)
2. afterwards, `ServiceB` kicks-in, then **_Chucker_** unable to show the request header in **_Request_** tab 

**_Okhttp_** team said this is intended: https://github.com/square/retrofit/issues/977#issuecomment-135422236

Therefore, we’re trying to `addNetworkInterceptor` instead for every services calls, e.g:

```
            .authenticator(if (token.isNullOrBlank()) Authenticator.NONE else RetrofitAuthenticator(token))
            .addInterceptor(chuckerInterceptor)
            .addNetworkInterceptor(object : Interceptor {
                override fun intercept(chain: Interceptor.Chain): Response {
                    val newRequest = chain.request().newBuilder()
                        // without this, our apps fails due to removed `Authorization` 
                        .apply {
                            if (token.isNullOrBlank().not()) header(
                                "Authorization",
                                "Bearer $token"
                            )

                            if (isDebug && baseUrl.contains("mock")) header(
                                "Prefer",
                                "dynamic=false"
                            )
                        }

                    return chain.proceed(if (token.isNullOrBlank()) chain.request() else newRequest)
                }
            })
            .build()
```

Previously without using `addNetworkInterceptor` as stated in the sample code above, our android apps is failed to access the resources/services (with http error code: `401`)

## :bomb: Steps to reproduce

1. Go to **_Chucker_** activity (from notification dialog)
2. Click on one of the `Network` tab
3. Scroll down to see list of endpoints/services
4. Clicks one e.g: `GET /endpoint/url` (from `ServiceB`)
5. Go to `Request` tab, there's no `Authorization: Bearer dumyyloremipsum` there

## :wrench: Expected behavior

Even though **_Okhttp_** remove the `Authorization` header, is it possible for **_Chucker_** to show authorization header provided when using `addNetworkInterceptors`

Or is there any workaround for my above implementation?

1. reordering the `addInterceptor(chcukerInterceptor)` to after `addNetworkInterceptor`
2. using `addInterceptor` to reinsert `Authorization` after `Okhttp` removed it

Both above workaround, the chucker still unable to show the key-value of `Authorization` header

## :camera: Screenshots

Show authorization header

This represents `ServiceA`
<img width="438" alt="Screen Shot 2021-01-13 at 9 06 44 PM" src="https://user-images.githubusercontent.com/7057959/104463002-d1291600-55e3-11eb-8548-852c7e0220d2.png">

Unable to show authorization header (but the endpoint is requires `Authorization` header)

This represents `ServiceB`
<img width="442" alt="Screen Shot 2021-01-13 at 9 08 36 PM" src="https://user-images.githubusercontent.com/7057959/104463262-2402cd80-55e4-11eb-9cac-64fd292dc454.png">

## :iphone: Tech info
 - Device: Xiaomi Redmi Note 7
 - OS: 9
 - Chucker version: 3.2.0

## :page_facing_up: Additional context

https://kotlinlang.slack.com/archives/CRWD6370R/p1610544821030700

**Comment by mochadwi** [comment]
seems like the same issue is already closed in here: https://github.com/ChuckerTeam/chucker/issues/474

will try to use the workaround above

**Comment by cortinico** [comment]
> Even though **_Okhttp_** remove the `Authorization` header, is it possible for **_Chucker_** to show authorization header provided when using `addNetworkInterceptors`

As suggested in #474, you should switch Chucker to be used as Network interceptor (with `addNetworkInterceptors`). 

It's unclear from the bug report if you already did it for chucker or you were referring to the other network interceptor you added below.

**Comment by MiSikora** [comment]
> will try to use the workaround above (will close this issue if it's works)

I wouldn't say that there is any workaround going on. `ChuckerInterceptor` acts as any other interceptor. It is aware of the traffic prior to its interception point. If applied as a network interceptor it fetches all of the network traffic up including interceptors applied before it in the chain. Same goes for an application interceptor, just for the application traffic.

**Comment by mochadwi** [comment]
Yes, it works when switching to `addNetworkInterceptor` apologize for the delays update & miss-understanding regarding interceptor! 

Closing this issue, thanks a lot for your answer~ @MiSikora @cortinico
