### ISSUE TITLE
Is there any plan to host the artifact on https://mvnrepository.com/.

### ISSUE THREAD

**Issue by TonyTangAndroid** [ChuckerTeam/chucker#56]
If the artifact is hosted on https://jitpack.io/, we could have security concerns. I know that it could be painful to get it work for the first time. We could leverage the plugin here https://github.com/vanniktech/gradle-maven-publish-plugin to minimize our effort.

**Comment by cortinico** [comment]
Hey @TonyTangAndroid 

> we could have security concerns

Which security concerns are you talking about? If you refer to XBI attacks and something similar to what was described here https://blog.autsoft.hu/a-confusing-dependency/ ...those kind of attacks are unrelated to JitPack and more related to your build.gradle configuration.

On the other hand, I was wondering if you're raising the issue as you're having problem accessing JitPack or not?

**Comment by koral--** [comment]
If chucker is published on maven central then another projects published there can depend on it.

**Comment by cortinico** [comment]
> If chucker is published on maven central then another projects published there can depend on it.

Is this a real blocker?
According to this page: https://maven.apache.org/repository/guide-central-repository-upload.html
Is not a real blocker. 

Ideally we could host Chucker on Maven Central as soon as we release 3.0.0

**Comment by koral--** [comment]
Thanks for pointing this out!
Last time I've checked there was a requirement that each dependency must be also available on central.

**Comment by vbuberen** [comment]
@cortinico 
Going to refresh the state of this issue. Are we going to redeploy to Maven?
Or we will do something like multiple sources to have some sort of backup?

**Comment by cortinico** [comment]
> Going to refresh the state of this issue. Are we going to redeploy to Maven?

Sure, I'm happy to explain to everyone.
Initially, @olivierperez hosted the first versions of Chucker on Bintray/JCenter. We then moved to JitPack as this simplifies the whole deployment process. Specifically:

* We don't have to deal with a GPG key, signing, key-sharing, etc.
* We get `-SNAPSHOTS` versions for every branch out of the box
* The release process is extremely streamlined as we need to only push a git tag to get a new release.

> Or we will do something like multiple sources to have some sort of backup?

I think we can definitely publish to Maven Central if the community is requesting it. This will have the benefit that other libraries on Central can easily depend on us. Moreover will overcome some of the potential security issues mentioned by @TonyTangAndroid. We just need to agree internally on the whole GPG key mgmt @vbuberen

**Comment by Sloy** [comment]
Hi! Have you discussed this topic any further?

For us, the biggest reason to prefer Maven Central or JCenter is build performance, since Jitpack is much slower. Many times our builds have stalled or even broken because of slow responses or downtimes from Jitpack.

(BTW we're just migrating from the original Chuck to Chucker, so thanks a lot!)

**Comment by cortinico** [comment]
> Hi! Have you discussed this topic any further?

Nope we haven't but I'd love raise the discussion on our Slack channel (you're welcome to join #chucker on Kotlinlang).

Seems like this is one of the most requested featured.
We're probably going to keep having JitPack as it's really useful to troubleshooting and ask feedbacks on Issues/PR.

**Comment by Sloy** [comment]
I agree that having Jetpack for snapshots and PRs is super useful. But for production builds it often causes some bottlenecks in CI builds. Maven Central or JCenter seem to be faster and more reliable historically.

Looking forward to any update on this topic :)

**Comment by LouisCAD** [comment]
JitPack, not Jetpack.

**Comment by Sloy** [comment]
Yea sorry, typo.

**Comment by marcorighini** [comment]
Hi @cortinico, do you have some updates on this? We cannot use Chucker because Jitpack was unrealiable lately.

**Comment by cortinico** [comment]
> Hi @cortinico, do you have some updates on this? We cannot use Chucker because Jitpack was unreliable lately.

Yes, we do have some little updates. We're definitely going to host the Chucker artifacts on Maven Central.
This is coming in the near future (I can't tell you an exact date right now).

**Comment by cortinico** [comment]
> Hi @cortinico, do you have some updates on this? We cannot use Chucker because Jitpack was unreliable lately.

Quick heads up: `3.2.0` is now available on Maven Central 🚀 
We've updated the readme with the descriptions about the deployments and the snapshots availability.

Please let us know if you encounter any issue with the artifacts.
