### ISSUE TITLE
Can we integrate chucker with Hybrid apps (using ionic 3 platform)??

### ISSUE THREAD

**Issue by kanika27gupta** [ChuckerTeam/chucker#574]
## :raising_hand: Do you want to develop this feature yourself?

- [ ] Yes
- [ ] No

**Comment by cortinico** [comment]
> Can we integrate chucker with Hybrid apps (using ionic 3 platform)??

If you use OkHttp for the network calls, then yes.
Otherwise that's not possible as of today.
