### ISSUE TITLE
AdUrl request is not getting tracked in chucker log

### ISSUE THREAD

**Issue by jitendratiwari** [ChuckerTeam/chucker#598]
## :iphone: Tech info
 - Device: 
 - OS: 
 - Chucker version:

**Comment by jitendratiwari** [comment]
I am using impluse sdk for ads in my project ,I am trying to track adUrl request and response using checker logs.
I am not getting anylogs related to adUrl,so do I need to add something  in chucker logs for third party sdk to track their request response.

**Comment by cortinico** [comment]
Please fill in the Issue template.
Also are you using Chucker as Application or Network interceptor?

**Comment by jitendratiwari** [comment]
As network interceptor.

**Comment by MiSikora** [comment]
I don't think there is anything actionable for us here but before I close I'll ask – how do you install `OkHttp` client or `ChuckerInterceptor` inside this SDK?

**Comment by jitendratiwari** [comment]
We are not installing any chucker interceptor  or http client inside the
SDK as its not in our control.
By any change if we use chucker as Application can we trace  adrequest in
chuckerlog

Regards,
Jitendra

**Comment by MiSikora** [comment]
So as I mentioned, there is nothing actionable for us here. Chucker works only when installed in an OkHttp client. You're looking for a proxy client but most likely such a service uses SSL pinning so you won't be able to inspect traffic.

**Comment by jitendratiwari** [comment]
Can it be possible with chucker app

**Comment by MiSikora** [comment]
No.

**Comment by jitendratiwari** [comment]
So y did u ask

Also are you using Chucker as Application or Network interceptor?

initially.

**Comment by cortinico** [comment]
> So y did u ask Also are you using Chucker as Application or Network interceptor?

Sorry I haven't realized that you're requesting to inpsect a request coming from an SDK where you don't have control over the HTTP Client. So my original question was irrelevant to your issue.
