### ISSUE TITLE
Fetch Chucker

### ISSUE THREAD

**Issue by mrgaric** [ChuckerTeam/chucker#61]
Hi
I added chucker to project but i get chuck
How am I fix it?

![image](https://user-images.githubusercontent.com/24540790/60451523-e83c2900-9c34-11e9-8166-9cf73230844e.png)

**Comment by mrgaric** [comment]
Sorry, it's my carelessness, I'm could not find ChuckerInterceptor in release brach

**Comment by cortinico** [comment]
Hey @mrgaric 
Sorry for the confusion. 

The `release` branch is fixed at the latest released stable version (2.0.4).
The `develop` branch contains the latest fixed and the upcoming version (3.x)

We renamed a lot of classes and now you can find `ChuckerInterceptor` only on `develop` (I anyway suggest to use the version `3.0.0-alpha1` of Chucker).

In the `release` branch the interceptor is called `ChuckInterceptor`.
I agree that is confusing, and I'm going to cleanup the Readme as soon as we release the `3.0.0` stable version (soon).

I hope this clarifies everything. If not please let me know.
