### ISSUE TITLE
Missing response information for all POST request

### ISSUE THREAD

**Issue by tprochazka** [ChuckerTeam/chucker#612]
It is maybe an issue on my side, but I'm not able to get any response information for all POST requests, GET works just fine.

![image](https://user-images.githubusercontent.com/172094/115750352-5ae14000-a398-11eb-9656-836475f7b347.png)

It is a limitation? bug? Or my issue please?

I'm using chucker 3.4.0 and okhttp lib 4.9.1

**Comment by MiSikora** [comment]
Do you actually get the response in the app from the server?

**Comment by tprochazka** [comment]
Yes. I get data and server return code 200.

Code looks like this:

        Request.Builder request = new Request.Builder().url(url)
        request.post(new FormBody.Builder().add(PARAM_USERID_TOKEN, getUserIdToken()).build());
        Response response = client.newCall(request.build()).execute();
        println("response: " + response.code());

**Comment by MiSikora** [comment]
You need to read and close body in order to make it available. You can read more [here](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-response-body/).

**Comment by tprochazka** [comment]
Yes. Of course, I'm doing that. Otherwise GET request will not work for me either. 

I have something like this

	public InputStreamReader openStream(Response response) throws IOException, ServerApiError {
		InputStream is = response.body().byteStream();

		//Charset detection according: Content-Type:text/html;charset=UTF-8
		String charset = sXmlEncoding;
		String contentType = response.header("Content-Type");
		if (contentType != null && contentType.contains("charset")) {
			charset = contentType.replaceAll("^.*=", "");
		}

		Charset charsetObj;
		try {
			charsetObj = Charset.forName(charset);
			sXmlEncoding = charset;
		} catch (Exception ex) {
			charsetObj = Charset.forName(sXmlEncoding);
		}

		return new InputStreamReader(checkForUtf8BOM(is), charsetObj);
	}

	private static InputStream checkForUtf8BOM(InputStream inputStream) throws IOException, ServerApiError {
		PushbackInputStream pushbackInputStream = new PushbackInputStream(inputStream, 3);
		byte[] bom = new byte[3];
		if (pushbackInputStream.read(bom) != -1) {
			if (!(bom[0] == (byte) 0xEF && bom[1] == (byte) 0xBB && bom[2] == (byte) 0xBF)) {
				pushbackInputStream.unread(bom);
			}
		}
		return pushbackInputStream;
	}


I have a problem just with POST
The only difference is this line

	request.post(new FormBody.Builder().add(PARAM_USERID_TOKEN, getUserIdToken()).build());

**Comment by MiSikora** [comment]
You still don't close the stream or it is not represented in the snippet. If you can share the project or a sample I can take a look at it. Otherwise I can only assume it's something on your end as it doesn't matter to `ChuckerInterceptor` what type of requests it is.

**Comment by tprochazka** [comment]
So. Yes. You have right. Thanks a lot! It was just a random coincidence that only one POST request in my app was not properly closed after reading, it is the reason why others GET request was working.

So this tool is also an awesome tool to detect this. Would be possible to somehow display the state of this request? Or interceptor has nothing until the stream is properly closed?

**Comment by MiSikora** [comment]
It kind of already shows. You can see that the the requests that were not closed are greyed out. It means that they are still in progress from interceptor's perspective. We can't explicitly show anything like `request not closed` because there is no API for it.
