### ISSUE TITLE
Add support for binary content (images)

### ISSUE THREAD

**Issue by OlliZi** [ChuckerTeam/chucker#64]
**Describe the solution you'd like**
Also show images in response tab:)

**Comment by OlliZi** [comment]
[patch.diff.zip](https://github.com/ChuckerTeam/chucker/files/3381826/patch.diff.zip)

**Comment by cortinico** [comment]
Hey @OlliZi 
Can I ask you to submit a pull request? Thanks :)

**Comment by OlliZi** [comment]
Izts my first time to do a PR. So, i have added a diff with the code in my comments above:) Or explain me to how to do a PR here on github:)

**Comment by OlliZi** [comment]
PR is open:
https://github.com/ChuckerTeam/chucker/pull/67

**Comment by cortinico** [comment]
Closed by #67
