### ISSUE TITLE
Chucker provide more information about what api call in the list

### ISSUE THREAD

**Issue by yehezkiell** [ChuckerTeam/chucker#642]
## :warning: Is your feature request related to a problem? Please describe
I'm using chucker a lot, but there is some issue that decreasing productivity so much imo. We also using graphql for the api call. So to find the query we need to figure it out which list is the right query. We need to open and close, back and forth to find the particular query. 
![74109420-9cb30b80-4b83-11ea-9444-bb84e95e0205](https://user-images.githubusercontent.com/17094969/124216454-8a42c480-db20-11eb-96af-e4cc4c7ef167.png)

## :bulb: Describe the solution you'd like
Can we extend chucker list class and make a custom view. We really need information about what query/mutation is this call like:
![74109420-9cb30b80-4b83-11ea-9444-bb84e95e0205](https://user-images.githubusercontent.com/17094969/124216591-cece6000-db20-11eb-8efd-1a7f8de54e07.png)

## :bar_chart: Describe alternatives you've considered
You can open chucker activity or chucker viewholder to be customable

## :raising_hand: Do you want to develop this feature yourself?
- [ ] Yes
- [x] No

**Comment by cortinico** [comment]
I believe we can clean this issue and track it under #69

**Comment by MiSikora** [comment]
I agree. And I would be really hesitant towards exposing customisable UI. As a long term goal I would potentially see having a separate backend/presentation artifact to which you can connect your own UI but definitely not customisable UI within the library.

**Comment by yehezkiell** [comment]
@MiSikora that will really help if we can consume the data from our project and create the custom UI with chucker data, thanks for the response

**Comment by cortinico** [comment]
> that will really help if we can consume the data from our project and create the custom UI with chucker data

Basically what #579 is about 👍
