### ISSUE TITLE
Conflicts related to duplicate classes in jetified-runtime modules while building the project

### ISSUE THREAD

**Issue by RahulSDeshpande** [ChuckerTeam/chucker#666]
## :writing_hand: Describe the bug
When I try to add `library` & library-no-op` to the app, there is some conflict related to duplicate classes in jetified-runtime modules.

## :bomb: Steps to reproduce

1. Add `library` & library-no-op` to the app
2. Build the project

## :wrench: Expected behavior
Project should be built successfully.

## :camera: Stack-trace
```kt
Duplicate class com.chuckerteam.chucker.BuildConfig found in modules jetified-library-3.5.0-runtime (com.github.chuckerteam.chucker:library:3.5.0) and jetified-library-no-op-3.5.0-runtime (com.github.chuckerteam.chucker:library-no-op:3.5.0)
Duplicate class com.chuckerteam.chucker.api.Chucker found in modules jetified-library-3.5.0-runtime (com.github.chuckerteam.chucker:library:3.5.0) and jetified-library-no-op-3.5.0-runtime (com.github.chuckerteam.chucker:library-no-op:3.5.0)
Duplicate class com.chuckerteam.chucker.api.ChuckerCollector found in modules jetified-library-3.5.0-runtime (com.github.chuckerteam.chucker:library:3.5.0) and jetified-library-no-op-3.5.0-runtime (com.github.chuckerteam.chucker:library-no-op:3.5.0)
Duplicate class com.chuckerteam.chucker.api.ChuckerInterceptor found in modules jetified-library-3.5.0-runtime (com.github.chuckerteam.chucker:library:3.5.0) and jetified-library-no-op-3.5.0-runtime (com.github.chuckerteam.chucker:library-no-op:3.5.0)
Duplicate class com.chuckerteam.chucker.api.ChuckerInterceptor$Builder found in modules jetified-library-3.5.0-runtime (com.github.chuckerteam.chucker:library:3.5.0) and jetified-library-no-op-3.5.0-runtime (com.github.chuckerteam.chucker:library-no-op:3.5.0)
Duplicate class com.chuckerteam.chucker.api.RetentionManager found in modules jetified-library-3.5.0-runtime (com.github.chuckerteam.chucker:library:3.5.0) and jetified-library-no-op-3.5.0-runtime (com.github.chuckerteam.chucker:library-no-op:3.5.0)
Duplicate class com.chuckerteam.chucker.api.RetentionManager$Period found in modules jetified-library-3.5.0-runtime (com.github.chuckerteam.chucker:library:3.5.0) and jetified-library-no-op-3.5.0-runtime (com.github.chuckerteam.chucker:library-no-op:3.5.0)

```

## :iphone: Tech info
 - Chucker version: **3.5.0**

**Comment by vbuberen** [comment]
Hey there. Could you share your app `build.gradle` file to see how you add both libraries into your project?

It looks like you add both dependencies as `implementation` instead of adding `library-no-op` as `implementation`, while `library` as `debugImplementation`.

**Comment by RahulSDeshpande** [comment]
@vbuberen 

This is how I have added dependencies in the app's `build.gradle.kts`:
```kt
debugImplementation("com.github.chuckerteam.chucker:library:3.5.0")
releaseImplementation("com.github.chuckerteam.chucker:library-no-op:3.5.0")
```

**Comment by cortinico** [comment]
> This is how I have added dependencies in the app's `build.gradle.kts`:

Are you sure about this? This kind of issue could be happening if you are applying `chucker` to a Android library module and for some reason the Gradle variant matching is not working properly.

Would you be able to provide a reproducer of some form?
Also could you try to `./gradlew :app:clean` and `./gradlew :app:assembleDebug` to verify that the issue is actually happening again?

**Comment by cortinico** [comment]
Small note: are you aware of any other dependency you're using that might be importing chucker? Might be worth taking a look at a Gradle scan if you can provide it.

**Comment by RahulSDeshpande** [comment]
@cortinico 
I tried cleaning the app multiple times previously, but the issue was not resolved.

😞 I now cleaned up my git local repo & gradle's local `.m2` folder as well, & now its working!!
Strangely!!
The app is getting built correctly!

Thanks though!!

**Comment by cortinico** [comment]
Great thanks for your feedback :)
