### ISSUE TITLE
java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object

### ISSUE THREAD

**Issue by theakashdev** [ChuckerTeam/chucker#669]
com.xxxxxxxx E/AndroidRuntime: FATAL EXCEPTION: IntentService[Chucker-ClearDatabaseService]
    Process: com.xxxxxx, PID: 27108
    java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = com.chuckerteam.chucker.internal.support.ClearDatabaseService$a$b)

**Comment by vbuberen** [comment]
I would kindly ask to fill you report using the template we provide. Otherwise we can't help you.
