### ISSUE TITLE
Add support for GraphQL

### ISSUE THREAD

**Issue by rnitame** [ChuckerTeam/chucker#69]
**Is your feature request related to a problem? Please describe.**
I don’t know the details at first glance. Because every request is a POST method to `/graphql`

ex)

![screenshot](https://user-images.githubusercontent.com/4950792/61429668-2a1ddc80-a962-11e9-82a9-6182ea95340e.png)

**Describe the solution you'd like**
I want to change `POST /graphql`  to used Query or Mutation name

**Describe alternatives you've considered**
Add processing to change the string in TransactionAdapter class when endpoint equals `/graphql` 
If there are other good ways, please suggest 🙏 

ref: https://graphql.org/learn/serving-over-http/#uris-routes

**Do you want to develop this feature yourself?**
yes

**Comment by cortinico** [comment]
> Do you want to develop this feature yourself?
> yes

Hey @rnitame 
Please let me know if you need some support on this,

> I want to change POST /graphql to used Query or Mutation name

Ideally I would add some extra informations but I would keep the full HTTP path.
Like if is a GraphQL request, Chucker could ideally parse the `operationName` from the body and display it? Also showing an extra icon for GraphQL requests might be valuable

**Comment by rnitame** [comment]
Thank you for idea! @cortinico 
My implement plan updated. What do you think?

![image](https://user-images.githubusercontent.com/4950792/61844977-6d38fc00-aedc-11e9-9185-9164fdc9714b.png)

`operationName` can probably be obtained from `requestBody` .

**Comment by rnitame** [comment]
PR is open. I currently development :)

**Comment by vbuberen** [comment]
@rnitame @cortinico @psh 
Hey guys, could someone provide some info on the status of this feature and what is required to make it to production? 
Is any help or discussion required?
