### ISSUE TITLE
Curl Request Issue with postman import

### ISSUE THREAD

**Issue by shubham-soni9** [ChuckerTeam/chucker#701]
## :bomb: Steps to reproduce

1. Share as curl command
2. Import as raw text in postman
3. You will get an error as args.startsWith

## :wrench: Expected behavior
<!- I should get imported

## :solution: Solution
Just add a semicolon from https:// to end. e.g. "https://www.google.com" (when i export it is exported as http://www.google.com without semicolon before https:// and after .com)

## :iphone: Tech info
 - Device:  no specific
 - OS:  no specific
 - Chucker version: 

## :page_facing_up: Additional context
Please solve this on priority.

**Comment by MiSikora** [comment]
Sorry but I'm having issues with understanding the problem. What semicolon are you speaking of? Can you show example cURL that is created by Chucker and the one that you expect? Or even better and example that we can execute?

I tried to execute cURL from Chucker in the console and everything works as expected. If there are some issues in Postman understanding valid cURLs then you need to report it to them.

> Please solve this on priority.

This is an OSS project on which we work in our free times. If it it something that is of priority to you we welcome contributions.

**Comment by MiSikora** [comment]
I'm closing the issue due to no actionable information. Feel free to reopen if there is some follow-up.
