### ISSUE TITLE
Multipart Upload Fails when chucker is used as Network Interceptor

### ISSUE THREAD

**Issue by RamolaWeb** [ChuckerTeam/chucker#702]
## :writing_hand: Describe the bug

While doing a multipart/form request to upload the file and adding the chucker as a network interceptor, I got the java.io.IOException: Stream Closed Error

## :bomb: Steps to reproduce

Do a multipart/form request and upload a file
You can see the exception
## :wrench: Expected behavior

Multipart/Form requests should handle properly

## :iphone: Tech info

 - Chucker version:3.5.2

**Comment by RamolaWeb** [comment]
<img width="934" alt="Screenshot 2021-10-07 at 21 29 01" src="https://user-images.githubusercontent.com/12547818/136421615-eaf55a1f-02b2-4c6f-b195-697ae8649321.png">

@MiSikora I am using https://github.com/wkh237/react-native-fetch-blob to upload the image in the react-native application. When I tried to integrate the chucker to intercept the network call, this issue was found. This library is using OkHttp under the hood provided by the react-native.

**Comment by MiSikora** [comment]
Unfortunately, there's not much we can do about it. And it is not Chucker-specific.

https://github.com/joltup/rn-fetch-blob/blob/dcbde6f7e12b666b9fe1c8c4a8e2cb04e0048326/android/src/main/java/com/RNFetchBlob/RNFetchBlobBody.java#L28

The linked library uses an input stream to transmit bytes, and one cannot read from input streams multiple times. You can ask authors to override `fun isOneShot(): Boolean` in the `RNFetchBlobBoddy` to return `true`. Chucker ignores and does not try to read one-shot bodies. However, it is currently available in the snapshot version only.

@cortinico @vbuberen Maybe we should upstream #544 to `3.x`?

**Comment by saumyabhatnagar2000** [comment]
Have we added this 

> No, let's not add anything new to `3.x`. People interested in this feature can use snapshot versions till we release `4.x`.

Have we added fix for this in `4.x` ?

**Comment by talhatsk** [comment]
is there any fix for this issue available ? @cortinico @vbuberen @MiSikora
