### ISSUE TITLE
Documention update for new method of implementation in Readme

### ISSUE THREAD

**Issue by BharathKmalviya** [ChuckerTeam/chucker#706]
## :writing_hand: Describe the bug

The example still has an old deprecated way to initialize the ChuckerInterceptor
```kotlin
val client = OkHttpClient.Builder()
                .addInterceptor(ChuckerInterceptor(context))
                .build()
```

## :wrench: Expected behavior
this should be the example according to latest version method
```kotlin
val client = OkHttpClient.Builder()
                .addInterceptor(ChuckerInterceptor.Builder(context))
                .build()
```

## :iphone: Tech info
 - Chucker version: 3.5.2

**Comment by MiSikora** [comment]
The constructor with `Context` as the only argument is not deprecated.

https://github.com/ChuckerTeam/chucker/blob/c9dec0b1c93b0bbb07b925f6f658db8c96c81134/library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt#L31

You might be referring to version `3.x` but it states the same.

https://github.com/ChuckerTeam/chucker/blob/6df6ec8afc3231752f3319a742caa75938f38a3c/library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt#L70-L71
