### ISSUE TITLE
Request size is shown as -1

### ISSUE THREAD

**Issue by vbuberen** [ChuckerTeam/chucker#714]
## :writing_hand: Describe the bug
`POST` request size for requests without payload shows invalid value `-1` in the version from `develop` branch

## :bomb: Steps to reproduce
1. Do some POST requests without payload
2. Open transaction details 

## :wrench: Expected behavior
Request size is shown as 0 or `-` 

## :camera: Screenshots
<img width="387" alt="Screenshot 2021-11-02 at 11 59 24" src="https://user-images.githubusercontent.com/13467769/139828141-39e420f8-57c5-4d07-a447-a0b602d366df.png">

## :page_facing_up: Additional context
I suspect this issue appeared after merging #696

**Comment by MiSikora** [comment]
I can take a look at it.

**Comment by MiSikora** [comment]
This bug wasn't introduced with #696. It is a result of not processing one-shot bodies added in #544.

https://github.com/ChuckerTeam/chucker/blob/5adc92ca22b644a5a64075a433fa5a6901b7e0bc/sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinHttpTask.kt#L80

Let's deal with it during #570. I'll update the description there, and I think we can close this one. Do you agree?

**Comment by vbuberen** [comment]
Yep, absolutely. Closing.
