### ISSUE TITLE
Activity exported tag - Android 12 requirements

### ISSUE THREAD

**Issue by RichardLiba** [ChuckerTeam/chucker#718]
## :writing_hand: Activity exported tag - Android 12 requirements
Android 12 build target requires all activities to have exported tag in manifest.

## :bomb: Steps to reproduce
1. Use latest stable release 3.5.2 version.
2. compile and target version - 31
3. Build application
4. See merged manifest values -> 

![Screenshot 2021-11-10 at 13 26 58](https://user-images.githubusercontent.com/32630888/141113892-80867335-a711-4ecb-8c6f-ba400bea1214.png)

5. See error ->

![Screenshot 2021-11-10 at 13 35 36](https://user-images.githubusercontent.com/32630888/141114300-feda46a0-1357-45d6-86ba-1bc9d83597b4.png)

**Comment by vbuberen** [comment]
For apps targeting Android 12 not all activities are required to specify `exported` tag. Only those with with intent filters defined. See: https://developer.android.com/about/versions/12/behavior-changes-12#exported

Activities from Chucker which you showed on your screenshot with AndroidManifest don't have intent filters. So I believe the error you are getting isn't due to Chucker. Be sure to check that your `MainActivity` has `exported` tag defined.

**Comment by RichardLiba** [comment]
Only one entry does not have exported in merged manifest then, these two activities -> I agree maybe that is not the issue but I found one intent -> 

<action
android:name="android.intent.action.CREATE_DOCUMENT"...

double clicking on this intent CREATE_DOCUMENT takes me to jetified library chucker with manifest.
Should this intent also be exported/not exported?

**Comment by vbuberen** [comment]
Please, read the doc that I provided in the previous message.

Also, do you confirm that the issue with build appeared only after adding Chucker and your project already has all required exported tags?

If you can't confirm that I would like to close this issue, since it is not related to Chucker.

**Comment by vbuberen** [comment]
@RichardLiba Were you able to solve the issue?

**Comment by RichardLiba** [comment]
Sorry for bothering you, it was these three activites ->
        <activity
            android:name="androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity"
            android:theme="@android:style/Theme" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
            </intent-filter>
        </activity>
        <activity
            android:name="androidx.test.core.app.InstrumentationActivityInvoker$EmptyActivity"
            android:theme="@android:style/Theme" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
            </intent-filter>
        </activity>
        <activity
            android:name="androidx.test.core.app.InstrumentationActivityInvoker$EmptyFloatingActivity"
            android:theme="@android:style/Theme.Dialog" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
            </intent-filter>
        </activity>
        
        
We have used workaround with merged and exported on names for these activities. we can build project with target 31 now.
