### ISSUE TITLE
Disable auto-scrolling for network request list

### ISSUE THREAD

**Issue by RiteshChandnani** [ChuckerTeam/chucker#729]
## :warning: Is your feature request related to a problem? Please describe
The network tab in Chucker not only shows the list of network requests that the app made but also shows the requests that are currently being made in the background, this is good and very useful but what is really annoying is that whenever a new request is made, the scroll position also changes right away to accommodate the new UI item added to the list.
The reason this is annoying is that I am usually looking for a particular request but the scroll keeps on changing every time a new request comes in.

## :bulb: Describe the solution you'd like
Add a flag or some configuration to disable the autoscrolling. We could also disable it completely if that makes more sense to you.

## :bar_chart: Describe alternatives you've considered
NA

## :page_facing_up: Additional context
NA

## :raising_hand: Do you want to develop this feature yourself?
- [ ] Yes
- [x] No

**Comment by MiSikora** [comment]
Thanks for the issue! I think it's better to not scroll at all on updates than to make it configurable.

**Comment by vbuberen** [comment]
Agree here that the screen shouldn't scroll at all during updates.

Just checked this behavior and seems that the described issue only happens on `3.x` releases, while in `develop` scroll position is saved while list of transactions updates.

@RiteshChandnani I would suggest you to switch to snapshot builds if this scrolling issue is something too annoying.

**Comment by RiteshChandnani** [comment]
> Agree here that the screen shouldn't scroll at all during updates.
> 
> Just checked this behavior and seems that the described issue only happens on `3.x` releases, while in `develop` scroll position is saved while list of transactions updates.
> 
> @RiteshChandnani I would suggest you to switch to snapshot builds if this scrolling issue is something too annoying.

Thanks! good to know that it's already fixed in `develop`, I can live with it for now, but just out of curiosity, any timeline for the next release?

**Comment by vbuberen** [comment]
No specific timeline at the moment.

However, I would suggest you to try out SNAPSHOT build, which is current `develop` stage and also has scroll thing fixed. Our snapshots are stable and you shouldn't worry that it will cause you any pains.

**Comment by RiteshChandnani** [comment]
> No specific timeline at the moment.
> 
> However, I would suggest you to try out SNAPSHOT build, which is current `develop` stage and also has scroll thing fixed. Our snapshots are stable and you shouldn't worry that it will cause you any pains.

Thanks @vbuberen but it seems like SNAPSHOT builds are not available, checked at - https://repo.maven.apache.org/maven2/com/github/chuckerteam/chucker/library/

**Comment by RiteshChandnani** [comment]
Sorry, I was looking at the wrong URL 🤦 

Looks like snapshot build requires compileSDK 31 but we are not there yet, will update here we fix it.
