### ISSUE TITLE
Sponsorship / Donations

### ISSUE THREAD

**Issue by GuilhE** [ChuckerTeam/chucker#734]
Hello,
The company I work for is organizing a donation wave to support projects/teams that are doing a tremendous job helping out the open source community. ChuckerTeam it's one of these, no doubt. 

Are you open for donations/sponsorship?

Regards.

**Comment by vbuberen** [comment]
Hello there. 

Thanks, we really appreciate such initiative. We totally open for such idea and will setup OpenCollective shortly. After setting things up we will share further information on how to proceed. 

Anything special you would like to find out or discuss in the meantime?

**Comment by GuilhE** [comment]
Hello @vbuberen for now that's all, I'll be waiting for the OpenCollective setup.

**Comment by cortinico** [comment]
Hey @GuilhE,
Thanks again for thinking at us 🙏 We're in the process of adding a "Donate" button on GitHub that will point to an OpenCollective. It should take no longer than a couple of other days. Thanks for your patience

**Comment by vbuberen** [comment]
Now we officially have `Sponsor` button, so everyone should be able to support us in case they want to.

**Comment by GuilhE** [comment]
Hello! Just a quick status, the Sponsor is not forgotten, some minor internal bureaucracies pushed the deadlines. This will happen, don't worry :)

**Comment by GuilhE** [comment]
Hello, 

The donation was made! 🎊 

We want to create a wave of support that can grow as it moves forward in time, allowing companies and individuals to participate within their scale and possibilities. And that’s why we’ve created the [Open Source Donation Wave](https://opensourcedonationwave.com/).
Please feel free to share it to hopefully widen the range of this initiative and start a movement that could create a ripple donation effect 😃.

Best regards, and thank you for Chucker once again.

**Comment by vbuberen** [comment]
Hi there. 
Thank you very much for this initiative and for the donation. 
Going to share info about the initiative in social media to spread the word.

**Comment by cortinico** [comment]
> The donation was made! 🎊

That made my day <3 Thanks for doing it!
