### ISSUE TITLE
Chucker not showing notification on Android 11 - Pixel 4

### ISSUE THREAD

**Issue by pratamawijaya** [ChuckerTeam/chucker#740]
## :writing_hand: Describe the bug
Chucker not show notification on android 11, i have tested my code on android 10, and it showing network request

## :bomb: Steps to reproduce
i have create chucker instance like these 
```
@Provides
    @Singleton
    fun getChuckInterceptorInstance(@ApplicationContext context: Context): ChuckerInterceptor {
        // Create the Collector
        val chuckerCollector = ChuckerCollector(
            context = context,
            // Toggles visibility of the push notification
            showNotification = true,
            // Allows to customize the retention period of collected data
            retentionPeriod = RetentionManager.Period.ONE_HOUR
        )

        return ChuckerInterceptor.Builder(context)
            .collector(chuckerCollector)
            .alwaysReadResponseBody(true)
            .build()
    }
```

## :wrench: Expected behavior
Chucker should showing notification for logging every network request and response

## :iphone: Tech info
 - Device: Pixel 4
 - OS: Android 11
 - Chucker version: 3.5.2

**Comment by MiSikora** [comment]
This will be kind of hard to debug.

On the off chance - can you check on Pixel 4 if the application does not have notifications turned off in the system settings?

**Comment by vbuberen** [comment]
I think there was something like notification being hidden in the shade and not appearing in the status bar.

**Comment by luongvo** [comment]
Maybe Do not disturb is turning on. Turning it off solves the issue for me.
