### ISSUE TITLE
HTTP FAILED: java.lang.ClassCastException: $Proxy10 cannot be cast to nl.qbusict.cupboard.convert.IndexBuilder$c

### ISSUE THREAD

**Issue by Hosythang22** [ChuckerTeam/chucker#757]
HTTP FAILED: java.lang.ClassCastException: $Proxy10 cannot be cast to nl.qbusict.cupboard.convert.IndexBuilder$c

Issue happen when build release, debug work well

**Comment by cortinico** [comment]
> HTTP FAILED: java.lang.ClassCastException: $Proxy10 cannot be cast to nl.qbusict.cupboard.convert.IndexBuilder$c

You're most likely using an ancient version of Chucker. We got rid of Cupboard more than a year ago. Please update and check again.

**Comment by MiSikora** [comment]
I'm closing this one. Feel free to reopen if you see the issue in newer versions.
