### ISSUE TITLE
ChuckerTeam in Release build

### ISSUE THREAD

**Issue by lazy-coder-10** [ChuckerTeam/chucker#769]
I know this is not a good practice to use ChuckerTeam in the release build but is it possible to invoke ChuckerTeam in the release build?

Following is my requirement : 

It is like the Developer option in android OS. Where user will tap on the button 5 times somewhere (Hidden) in the app and the ChuckerTeam will be invoked. Now that particular user can see her API logs in the notification. 

Let me know if it is possible ASAP. 

Thank you

**Comment by cortinico** [comment]
You can technically by doing this in your build.gradle

```
dependencies {
-  debugImplementation "com.github.chuckerteam.chucker:library:3.5.2"
-  releaseImplementation "com.github.chuckerteam.chucker:library-no-op:3.5.2"
+  implementation "com.github.chuckerteam.chucker:library:3.5.2"
}
```

Plus you'll have to make sure you configure Chucker to show the notification only on DEBUG mode. Finally you can fire the `ChuckerActivity` whenever you wish (say when you click this hidden button).

Also as you said, it's not good practice as your users can discover and open this activity as well.
