### ISSUE TITLE
Select the entire text of the response/request body on "Select all"

### ISSUE THREAD

**Issue by perihanmirkelam** [ChuckerTeam/chucker#773]
<img width="379" alt="image" src="https://user-images.githubusercontent.com/24833235/154265854-b0ed0860-6419-44c4-b9a5-53416cb48d6e.png">

## :warning: Is your feature request related to a problem? Please describe
When I touch "Select all" on long-press, it allows to select only the field-value pair instead of selecting the entire response/request body. Also cannot be selected manually with cursors. 

## :bulb: Describe the solution you'd like
It would be very handy to be able to select the entire or part of response/request body to copy&paste anywhere.

## :raising_hand: Do you want to develop this feature yourself?

- [ ] Yes
- [X] No

**Comment by MiSikora** [comment]
Thanks for the issue. I'll close this one because it is tracked by #184.
