### ISSUE TITLE
Add function to generate a file of transactions (without immediately exporting)

### ISSUE THREAD

**Issue by jd565** [ChuckerTeam/chucker#783]
## :warning: Is your feature request related to a problem? Please describe
We currently use chucker in our app and find it is a really helpful tool for debugging issues. We are currently working on automating our internal bug reporting tooling for our QA team. The basic flow is they can shake the device and write the bug report and it will appear in asana/jira/whatever.

What we would like to do is when they submit a bug report automatically get some logs from chucker and upload that file with the bug report, so we can look through the network calls if we think that will help debugging the issue.

## :bulb: Describe the solution you'd like
Right now chucker has all the logic available to write a file with all this information in. What I would like is if there was a function that we could call to create the file - either then telling us where this file is, or allowing us to pass in a file/path that we want chucker to write to.

## :bar_chart: Describe alternatives you've considered
Without this we would resort to writing a manually SQL query and copying code out of chucker to implement the same thing.

## :page_facing_up: Additional context
I think it would be useful to provide some parameters to allow you to specify a certain timeframe or number of transactions (as getting all the chucker transactions can take an awful long time), so something like

`suspend fun writeChuckerLogs(maxTransactions: Long?, timeframe: Duration?, outputFile: File?): File`

## :raising_hand: Do you want to develop this feature yourself?
- [x] Yes
- [ ] No
Would be happy to develop feature, but also happy if anyone else wants to give it a go

**Comment by cortinico** [comment]
> What I would like is if there was a function that we could call to create the file - either then telling us where this file is, or allowing us to pass in a file/path that we want chucker to write to.

It sounds reasonable to me to add this functionality. Feel free to send a PR 👍

**Comment by jd565** [comment]
@cortinico PR above 😄

**Comment by cortinico** [comment]
> @cortinico PR above 😄

Thanks for doing it 🙏 I'll try to review it in the next days or within the weekend

**Comment by jd565** [comment]
This has been implemented and merged now
