### ISSUE TITLE
Pending Intent can have one of FLAG_IMMUTABLE or FLAG_MUTABLE

### ISSUE THREAD

**Issue by usmanabid09** [ChuckerTeam/chucker#786]
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

**Comment by cortinico** [comment]
We already do have this support:

https://github.com/ChuckerTeam/chucker/blob/28353fa6beab968e6106574b420549ef9220c1a6/library/src/main/kotlin/com/chuckerteam/chucker/internal/support/NotificationHelper.kt#L135-L139

It was done in this PR:
- https://github.com/ChuckerTeam/chucker/pull/593
