### ISSUE TITLE
Volley Support

### ISSUE THREAD

**Issue by Shrikant-B** [ChuckerTeam/chucker#788]
## :warning: Is your feature request related to a problem? Please describe
In one of our projects we are using Volley for networking which doesn't have interceptors like in Retrofit/OkHttp. As per the integration documentation we need OkHttp client to inject ChuckerInterceptor, there no way to do it with Volley.

## :bulb: Describe the solution you'd like
A way to inject ChuckerInterceptor with Volley when we init requestQueue to keep the integration at single place and no to do it at each request level.

## :raising_hand: Do you want to develop this feature yourself?
Can offer some help if needed

**Comment by cortinico** [comment]
This was briefly discussed in https://github.com/ChuckerTeam/chucker/issues/224 and linked issue.

I think it's unlikely that we support Volley at the moment, but with the upcoming refactoring of the data layer, we might be able to offer some extensibility
