### ISSUE TITLE
Configuration with name 'debugImplementation' not found

### ISSUE THREAD

**Issue by javimar** [ChuckerTeam/chucker#790]
Hello just was wondering if there is support for kotlin dsl in gradle.kts files since I am getting the error both for both release and debug.

"debugImplementation" (com.github.chuckerteam.chucker:library:$version)
"releaseImplementation" (com.github.chuckerteam.chucker:library-no-op:$version)

Thanks!!

**Comment by cortinico** [comment]
You should be able to use:
```
    debugImplementation("com.github.ChuckerTeam.Chucker:library:$version")
    releaseImplementation("com.github.ChuckerTeam.Chucker:library-no-op:$version")
```

Like here: https://cs.github.com/CarlosEsco/Neko/blob/ddca1043310541be17f31fa7974216715c25f9be/app/build.gradle.kts#L170
