### ISSUE TITLE
ViewBinding crashes with NPE when adding chucker dependency

### ISSUE THREAD

**Issue by luchoeli** [ChuckerTeam/chucker#792]
## :writing_hand: Describe the bug

Hi i'm implementing ViewBinding in a fragment as the [official documentation](https://developer.android.com/topic/libraries/view-binding#fragments) says, and i'm getting a NullPointerException just when chucker dependency is added
 
## :bomb: Steps to reproduce

1. Add Chucker dependency  on build.gradle file app module
```
dependencies {
  debugImplementation "com.github.chuckerteam.chucker:library:3.5.2"
  releaseImplementation "com.github.chuckerteam.chucker:library-no-op:3.5.2"
}
```
2. implement viewBinding on a fragment as [documentation ](https://developer.android.com/topic/libraries/view-binding#fragments)says (no need to insert any interceptor or any chucker code)
```

    private var _binding: ResultProfileBinding? = null
    // This property is only valid between onCreateView and
    // onDestroyView.
    private val binding get() = _binding!!

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        _binding = ResultProfileBinding.inflate(inflater, container, false)
        val view = binding.root
        return view
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }
    
```
3. Build an run
4. See error NPE error on the first fragment that reads  binding variable

## :iphone: Tech info
 - Device: Motorola Moto G3
 - OS: Android 6.0
 - Chucker version:  latest version, 3.5.2

**Comment by MiSikora** [comment]
Can you provide a sample project that reproduces it?
