### ISSUE TITLE
How do we avoid to intercept selective API ?

### ISSUE THREAD

**Issue by wahyupermadie** [ChuckerTeam/chucker#793]
Hi, I want to ask is it possible for Chucker to set an exception for selective API Request to not show in the interceptor list ?
for example, I have an API request "api/v1/getuser" I want to this request not showing in chuker network request list

**Comment by cortinico** [comment]
Nope that's not possible as of today. You can redact some fields however, not sure if that is helpful for you.

**Comment by wahyupermadie** [comment]
thank you for the response @cortinico , yap I think it's not possible, my point is I want to avoid showing `restriction data` in Chucker View, for example, exclude endpoint that contains data of `lat lng, address, etc`

**Comment by cortinico** [comment]
Nope that's not really possible as of today.

**Comment by MiSikora** [comment]
Closing as a duplicate of #266.
