### ISSUE TITLE
addBodyDecoder Support return the decoded Content-Type

### ISSUE THREAD

**Issue by kongnanlive** [ChuckerTeam/chucker#813]
## :warning: Is your feature request related to a problem? Please describe
```kotlin
class JSONDecoder : BodyDecoder {

    override fun decodeRequest(request: Request, body: ByteString): String? {
        return null
    }

    override fun decodeResponse(response: Response, body: ByteString): String? {
        val header = response.header("Content-Type")
        return if (header == "application/encrypted") {
            AESCrypt().decryptBase64(body.toByteArray())
        } else {
            null
        }
    }
}
```

## :bulb: Describe the solution you'd like
The above is my decoder. You can see that the Content-Type is "application/encrypted". After the decoding is completed, the output returned to the chucker is "application/json".

## :page_facing_up: Additional context
when i see full Chucker UI, I see not well formatted json but a string of text.
because Content-Type is not  "application/json"

## :raising_hand: Do you want to develop this feature yourself?
No

**Comment by cortinico** [comment]
> After the decoding is completed, the output returned to the chucker is "application/json".

What do you mean?

The `BodyDecoder` API only allows you to decode the body, you can't edit the `Content-Type`. Therefore, you're responsible for the visualization at this stage.

The suggestion is to either: 
- Use your own Json beautifier and do something similar to what we do here https://github.com/ChuckerTeam/chucker/blob/7e7c6a2edf820f423319a07946fe0505ef4ca8b4/library/src/main/kotlin/com/chuckerteam/chucker/internal/support/FormatUtils.kt#L55-L62
- Move this logic to its own OkHTTP Interceptor (before Chucker) so you'll be able to edit the whole response object (Body & Content-Type)
