### ISSUE TITLE
Programmatically interact with logs

### ISSUE THREAD

**Issue by rubinbasha** [ChuckerTeam/chucker#819]
## :bulb: Programmatically interact with logs
Greetings and thank you for the great work with this interceptor. It does make our QA process much easier and I am very grateful for the plug and play solution.
I would like to ask if there is a feature or if it could be implemented if not there yet.
I would like to actually get 2 features that are closely related.
1- is there / expose some  way to trigger the sharing of the currently captured logs programmatically without needing to open the system tray notification?
2- is there / expose some  way to trigger the flushing the currently captured logs programmatically without needing to open the system tray notification?

Thank you in advance

**Comment by cortinico** [comment]
> 1- is there / expose some way to trigger the sharing of the currently captured logs programmatically without needing to open the system tray notification?
> 2- is there / expose some way to trigger the flushing the currently captured logs programmatically without needing to open the system tray notification?

I believe what you're asking for is essentially this PR right #784 ?

**Comment by rubinbasha** [comment]
it does seems to fulfil at least the first request, I could not see from the PR if it is possible to flush the logs that were gathered before though

**Comment by cortinico** [comment]
> if it is possible to flush the logs that were gathered before though

You can use the timeStamp parameter to control how much content you want dumped on file.

**Comment by rubinbasha** [comment]
yep that can be used and I am looking forward to have this PR merged so I can start using it. 
Nonetheless a way to just programmatically flush everything would be a nice to have to free up user storage in the long run

**Comment by cortinico** [comment]
> Nonetheless a way to just programmatically flush everything would be a nice to have to free up user storage in the long run

You can use the RetentionManager to configure how long you want to retain user data.

**Comment by cortinico** [comment]
Nope not really, we don't generally give ETAs

**Comment by rubinbasha** [comment]
I saw that the programmatic interaction with the logs has been merged. I wanted to ask about some sample on how to use that feature as I don't seem to find it in the readme.

**Comment by cortinico** [comment]
> @cortinico I saw that the programmatic interaction with the logs has been merged. I wanted to ask about some sample on how to use that feature as I don't seem to find it in the readme.

You can find samples about it inside the sample app.

This is the code needed to export the log to file:
https://github.com/ChuckerTeam/chucker/blob/d0d51f9c655e352ba3ac29cca40f1398633ed4f5/sample/src/main/kotlin/com/chuckerteam/chucker/sample/MainActivity.kt#L48-L61

From there you can manipulate and read/interact with the file as you wish.

**Comment by rubinbasha** [comment]
thank you for the sample code. I today tried to get the latest snapshot but had problems getting it. Nonetheless I will just wait until the feature is released in a new stable release.
