### ISSUE TITLE
"Share as text" > Slack does not work

### ISSUE THREAD

**Issue by ColtonIdle** [ChuckerTeam/chucker#83]
Trying to share these responses through the Slack android app fails because it pastes into the "Title" field in slack.

If you open up chrome, select any text, and share through slack, you can see that the "Title" field does not even show up in Slack and instead it pastes the output into the message field, so it seems like this isn't something necessarily wrong with the Slack app as other apps can share correctly into it.

Edit: Occurs in latest stable and beta

**Comment by cortinico** [comment]
Looks like it's not a Chucker issue but a problem with Slack if we share more than 500 chars.
https://stackoverflow.com/questions/52440123/android-to-slack-sharing-issue

I've also tried setting a `Intent.EXTRA_SUBJECT` in the sharing intent but that doesn't fix.

https://github.com/ChuckerTeam/chucker/blob/397ea2084d8f95c7bab9575370c639d7f11b3e0e/library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionActivity.java#L143-L147

**Comment by ColtonIdle** [comment]
Thanks for giving it a shot.
