### ISSUE TITLE
Intercept WebView Requests

### ISSUE THREAD

**Issue by ahna92** [ChuckerTeam/chucker#855]
## :bulb: Describe the solution you'd like
Some applications have mix flows that requires to open a website inside webViews, 
Would be great to be able to debug requests responses there as well 

## :page_facing_up: Additional context
Might be useful to use WebClient's [shouldInterceptRequest](https://developer.android.com/reference/android/webkit/WebViewClient.html#shouldInterceptRequest(android.webkit.WebView,%20android.webkit.WebResourceRequest)) 

Might face a spamming issue while fetching css and images 

## :raising_hand: Do you want to develop this feature yourself?

- [X] Yes
- [ ] No

**Comment by cortinico** [comment]
> Would be great to be able to debug requests responses there as well

This is already possible. You can use the `shouldInterceptRequest` method as you suggest.
There are plenty of guides on the internet about it already: https://artemzin.com/blog/use-okhttp-to-load-resources-for-webview/

Closing as there is nothing actionable 👍

**Comment by ahna92** [comment]
Hi @cortinico 

I've built a `ChuckerWebViewHelper` class to enable WebView tracking , 
It was not straightforward and had to jump through some hoops :

- `WebvViewClient` method `shouldInterceptRequest` does not support http body requests ->  [google issue ](https://issuetracker.google.com/issues/119844519)
- Need to support cookies, so had to work with `CookiesManger`

**Classes to add** 
- [ChuckerWebViewHelper.kt](https://gist.github.com/ahna92/6245ddf39397009c981ebcfc4b2cb00f#file-chuckerwebviewhelper-kt)
- [SyncCookieHandler.kt](https://gist.github.com/ahna92/6245ddf39397009c981ebcfc4b2cb00f#file-synccookiehandler-kt)

**Examples**

- [SimpleWebViewFragment.kt](https://gist.github.com/ahna92/6245ddf39397009c981ebcfc4b2cb00f#file-mywebviewfragment-kt)
- [AdvancedWebViewFragment.kt](https://gist.github.com/ahna92/6245ddf39397009c981ebcfc4b2cb00f#file-mywebviewfragment2-kt)

It's highly customizable
```kotlin
ChuckerWebViewHelper
    .enable(true)
    .addWebViewClient(webView)
    .setOkHttpClient(builder.build())
    .addInterceptHost("example.com", "my.website.com")
    .interceptAllHosts(false)
    .addInterceptFileExtension("json", "jpg")
    .interceptAllFileExtension(flase)
    .handleRequestsWithPayload(true)
    .interceptPreflight(false)
``` 

I still feel this helper should be part of the library for easy plug and play integration 
like this [IOS equivalate library](https://github.com/kasketis/netfox)

If you like I can create a PR , 
if not I'll just leave this comment here for who needs this helper 

Full Helper documentation [here ](https://medium.com/airasia-com-tech-blog/android-network-traffic-tracking-79d2bb957bc2) , scroll to `Chucker with WebViews` section

**Comment by cortinico** [comment]
Thanks for looking into this @ahna92 and for sharing your findings 👍
It seems you're using Chucker transparently, so you can simply create a library with your classes and publish it on Github no? Agree that having a util class would help, but this feels a bit too specific and I'm unsure if we're willing to maintain it in the long run.

**Comment by ahna92** [comment]
something like `chucker-webview` yeah can do that too
