### ISSUE TITLE
Chucker produce build issue in projects with kotlin gradle plugin 1.4.32(Kotlin incompatible version)

### ISSUE THREAD

**Issue by nasrabadiAM** [ChuckerTeam/chucker#867]
## :writing_hand: Describe the bug
I can't build My project When I use Chucker(SNAPSHOT version) in it, with Kotlin Gradle plugin version 1.4.32 till 1.5.32.

With Kotlin plugin version 1.6.0 and higher, project(SNAPSHOT version) will built Successfully without any error. 
Stable version of Chucker (3.5.2) will work and compile correctly on any version of Kotlin plugin.

## :bomb: Steps to reproduce
Checkout [this repository](https://github.com/nasrabadiAM/chucker-incompatibility) and try to build and run the project.
Then you get this error during build: 
```error
/Users/user/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.7.10/bac80c520d0a9e3f3673bc2658c6ed02ef45a76a/kotlin-stdlib-common-1.7.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.4.2.
```
This issue will remain after clean, and invalidate cache.

## :wrench: Expected behavior
Build the project successfully without any problem in different Kotlin plugin versions with Chucker SNAPSHOT version.

## :camera: Screenshots
Kotlin Gradle Plugin: 1.4.32
<img width="1209" alt="Screen Shot 2022-08-10 at 16 13 24" src="https://user-images.githubusercontent.com/31126059/183902161-a32d16cb-8f3d-49d8-a0e3-41ffcf5ba005.png">

Kotlin Gradle Plugin: 1.5.32
<img width="1217" alt="Screen Shot 2022-08-10 at 16 30 14" src="https://user-images.githubusercontent.com/31126059/183901860-b17db398-f8b2-48e4-8728-e48e0b56eaf2.png">

## :iphone: Tech info
 - Device: Mac book m1 pro
 - OS: OSX
 - Library: Chucker version: 4.0.0-SNAPSHOT
 - IDE: Android Studio Chipmunk 2021.2.1 patch 2
- AGP: 7.3.3

**Comment by vbuberen** [comment]
Snapshot isn't considered as something that has to be stable and work everywhere. There are stable releases for stable work.

**Comment by nasrabadiAM** [comment]
I agree with you, but as you mentioned in this issue #795, I should use snapshot version till the next release, so what i need is a workaround to build my project(except changing the Kotlin version). if there is any solution to do this, please tell me about it. In that way I can fix it, and I will create a MR.

**Comment by nasrabadiAM** [comment]
And my second question is how stable versions of Chucker work without this incompatibility issue with projects with different Kotlin versions?

**Comment by cortinico** [comment]
> except changing the Kotlin version

Why bumping the Kotlin version is a problem for you?
You can force a transitive dependency on Gradle like:
https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#sec:enforcing_dependency_version
