### ISSUE TITLE
use Chucker in Stage build variant

### ISSUE THREAD

**Issue by Kaaveh** [ChuckerTeam/chucker#868]
As document says, we must added `Checker` dependencies like this:

```gradle
dependencies {
  debugImplementation "com.github.chuckerteam.chucker:library:3.5.2"
  releaseImplementation "com.github.chuckerteam.chucker:library-no-op:3.5.2"
}
```

But, what about other build variants like `stage` that we want to use checker in it?

**Comment by vbuberen** [comment]
The same way as for debug or release. Please search for info on how to work with build variants.

**Comment by Kaaveh** [comment]
@vbuberen I searched in issues for more info, But not found any useful info. Please could you reference some cleat info about how to work with build variants?

**Comment by Kaaveh** [comment]
Finally, I found the solution. For those in the future who seeking the answer:

```gradle
dependencies {
    debugImplementation("com.github.chuckerteam.chucker:library:3.5.2")
    "stagingImplementation"("com.github.chuckerteam.chucker:library:3.5.2")
    releaseImplementation("com.github.chuckerteam.chucker:library-no-op:3.5.2")
}
```

**Comment by Breens-Mbaka** [comment]
This worked thanks ❤️

**Comment by vbuberen** [comment]
> I searched in issues for more info, But not found any useful info. Please could you reference some clear info about how to work with build variants?

I meant that you should search on how to work with build variants in Android in general in Google, etc., not in Chucker repo.
