### ISSUE TITLE
Add export function to API (.har file)

### ISSUE THREAD

**Issue by BluestormDNA** [ChuckerTeam/chucker#871]
## :warning: Is your feature request related to a problem? Please describe

As of https://github.com/ChuckerTeam/chucker/pull/784 Chucker does have a way to export transactions as a .txt file, but it lacks the ability to export as .har format that was included in https://github.com/ChuckerTeam/chucker/pull/696.
A similar function should be added to export to .har too.

## :bulb: Describe the solution you'd like

A similar function as `ChuckerCollector` `writeTransactions` should be created. Something like `writeTransactionsHar`

## :bar_chart: Describe alternatives you've considered

Ideally the export functions should be merged and use a parameter to choose for plain text or .har format
`writeTransactions(format: ExportFormat)` `ExportFormat`could be a sealed class or enum with `PlainText` and `Har` fields.

## :raising_hand: Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

**Comment by cortinico** [comment]
> A similar function as `ChuckerCollector` `writeTransactions` should be created. Something like `writeTransactionsHar`

This looks like a good addition. However please add a `exportFormat` parameter to `writeTransactions` which is LOG by default but allows to have `HAR` as well.

**Comment by BluestormDNA** [comment]
@cortinico see https://github.com/ChuckerTeam/chucker/pull/880
Please be aware that the ignore test visibility is there because HarUtils only exposes a suspend fun and i needed the underlying blocking method.
I'll await comments.
