### ISSUE TITLE
OKhttp Mock server unit test failures

### ISSUE THREAD

**Issue by RanjithRagavan** [ChuckerTeam/chucker#878]
After adding the Chucker interceptor to our OKhttp client. Unit test casing using OKhttp mocker server test cases fails with following error:

class java.lang.Object cannot be cast to class android.app.NotificationManager (java.lang.Object is in module java.base of loader 'bootstrap'; android.app.NotificationManager is in unnamed module of loader 'app')
java.lang.ClassCastException: class java.lang.Object cannot be cast to class android.app.NotificationManager (java.lang.Object is in module java.base of loader 'bootstrap'; android.app.NotificationManager is in unnamed module of loader 'app')
	at com.chuckerteam.chucker.internal.support.NotificationHelper.<init>(NotificationHelper.kt:39)
	at com.chuckerteam.chucker.api.ChuckerCollector.<init>(ChuckerCollector.kt:32)
	at com.chuckerteam.chucker.api.ChuckerCollector.<init>(ChuckerCollector.kt:26)
	at com.chuckerteam.chucker.api.ChuckerInterceptor.<init>(ChuckerInterceptor.kt:37)
	at com.chuckerteam.chucker.api.ChuckerInterceptor.<init>(ChuckerInterceptor.kt:31)

**Comment by cortinico** [comment]
> After adding the Chucker interceptor to our OKhttp client. Unit test casing using OKhttp mocker server test cases fails with following error:

You should not use Chucker in your Unit tests.
What is happening for you is that Chucker is trying to show a notification by grabbing the `NotificationManager`

```
context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
```

I would suggest you either:
1. Conditionally apply the OkHTTP Chucker interceptor if you're on test environment
2. Use the `no-op` artifact for your tests like:

```
// for tests in the `test` folder
testImplementation "com.github.chuckerteam.chucker:library-no-op:3.5.2"
// for tests in the `androidTest` folder
androidTestImplementation "com.github.chuckerteam.chucker:library-no-op:3.5.2"
```
