### ISSUE TITLE
Provide an option to remove "errors" tab

### ISSUE THREAD

**Issue by ColtonIdle** [ChuckerTeam/chucker#88]
I use a few other crash reporters and crash viewers built into my application. The fact that Chucker added this onto Chuck is nice, but I want to get rid of it so my team doesn't get confused about whether or not we should be using it vs our other error reporters. During Chucker setup, it'd be nice to just opt-out of having the error feature showing/working.

**Comment by cortinico** [comment]
@ColtonIdle 
Are you suggesting a way to hide the "Errors" tab right?

**Comment by ColtonIdle** [comment]
Yep. Basically to only have the original functionality of chuck. Which is to inspect network traffic because I already use other tools for errors.

**Comment by cortinico** [comment]
> Yep. Basically to only have the original functionality of chuck. Which is to inspect network traffic because I already use other tools for errors.

I see. As a side note: Chucker is not capturing crashes unless you explicitly call `collector.onError()`. So the Error tab won't be populated automatically.

**Comment by uOOOO** [comment]
I'll PR after #98 is merged.

**Comment by vbuberen** [comment]
Would like to return to this question. I haven't seen much feedback or requests about error reporting feature since I joined the team, so it just gives some points to my suggestion of removing this functionality at all and making Chucker focused on network only. 

I believe that it is better to focus on something in such tool and do it great. 
So I suggest to remove `Errors` tab at all.

**Comment by cortinico** [comment]
I'm also in for removing it. Maybe we want to loop in with @olivierperez since he initially developed it. Are you actually using this feature? I would love to understand what's the adoption rate of it.

**Comment by olivierperez** [comment]
Hi, I'm ok too. This feature seems to be unused.
Can we at least make a poll on Twitter to ask people if the want to keep it or drop it?

**Comment by vbuberen** [comment]
Pool is a great idea. Let's do it :)

**Comment by cortinico** [comment]
I'd rather create a poll as a Github Issue as the majority of our users are there. We can set the issue as sticky and have a deadline say 2/3 weeks. People can vote using reactions like:

👍 Let's keep the feature
👎 Let's remove the feature
👀 See comment below

**Comment by vbuberen** [comment]
@cortinico Ok, I will create such issue. But I also would like to ask you to also post the link to tbis issue in Twitter, since your account is the most popular among us.

**Comment by cortinico** [comment]
Sure let's do that 👍

**Comment by vbuberen** [comment]
Closing this one due to deprecation of `Errors` tab
