### ISSUE TITLE
How can I log other events on Chucker?

### ISSUE THREAD

**Issue by JoeRakhimov** [ChuckerTeam/chucker#883]
## :warning: Is your feature request related to a problem? Please describe

It is taking a lot of time for debugging data exchange with Algolia (more about Algolia: https://www.algolia.com)

## :bulb: Describe the solution you'd like

I want to log requests and responses from Algolia on Chucker. Maybe is there some methods to log custom events?

## :bar_chart: Describe alternatives you've considered

There are some libraries with logging console but I want to keep all data exchange with backend and Algolia in one place.

## :page_facing_up: Additional context

I am just asking for method for logging custom events.

## :raising_hand: Do you want to develop this feature yourself?

- [ ] Yes
- [x] No

**Comment by cortinico** [comment]
Sadly this is not easily possible as of today. If you're communicating with Algolia via HTTP and you manage to route the traffic on the OkHTTP client, then Chucker will work fine.

Logging custom events was proposed here: #853

As of now we don't have a public API to do so and we would need to reword a bit the internals to allow this.
