### ISSUE TITLE
file descriptor not release

### ISSUE THREAD

**Issue by aBenVip** [ChuckerTeam/chucker#885]
## :writing_hand: Describe the bug

file descriptor not release

## :wrench: Expected behavior

lr-x------ 1 u0_a101 u0_a101 64 2022-09-14 23:34 200 -> /data/data/com.staging/files/chucker-1 (deleted)
l-wx------ 1 u0_a101 u0_a101 64 2022-09-14 23:34 201 -> /data/data/com.staging/files/chucker-2 (deleted)
lr-x------ 1 u0_a101 u0_a101 64 2022-09-14 23:34 202 -> /data/data/com.staging/files/chucker-2 (deleted)
l-wx------ 1 u0_a101 u0_a101 64 2022-09-14 23:34 203 -> /data/data/com.staging/files/chucker-3 (deleted)
l-wx------ 1 u0_a101 u0_a101 64 2022-09-14 23:34 204 -> /data/data/com.staging/files/chucker-4 (deleted)
lr-x------ 1 u0_a101 u0_a101 64 2022-09-14 23:34 205 -> /data/data/com.staging/files/chucker-3 (deleted)
lr-x------ 1 u0_a101 u0_a101 64 2022-09-14 23:34 206 -> /data/data/com.staging/files/chucker-4 (deleted)

## :iphone: Tech info
 - Device: OPPO FINDX
 - OS: 11
 - Chucker version: 3.3.2

**Comment by aBenVip** [comment]
@vbuberen

**Comment by cortinico** [comment]
> file descriptor not release

Closing as the issue report contains nearly none information to help us debug.
Also please don't ping people directly.

**Comment by aBenVip** [comment]
oh , sorry , this is a file descriptor  leak , i not have more info,  i provider fd folder list , i think can help found this issue

**Comment by aBenVip** [comment]
![image](https://user-images.githubusercontent.com/24616560/190545304-9998c144-de42-4ea1-922c-14ab8f541816.png)
and have "too many files open" in logcat

**Comment by aBenVip** [comment]
so i think some file not call close , maybe /data/data/com.staging/files/chucker-xx
