### ISSUE TITLE
Publish on other maven repository

### ISSUE THREAD

**Issue by BugsBunnyBR** [ChuckerTeam/chucker#896]
JitPack goes offline way too often, having the library artefacts hosted there causes troubles all projects when that maven repository is offline. Today we had hours of downtime where we couldn't compile our apps in the CIs.

**Comment by MiSikora** [comment]
Chucker is already distributed to Central and you can [configure](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:repository-content-filtering) Gradle to filter repository content.

**Comment by BugsBunnyBR** [comment]
Sorry, but this is not what I meant.
Without adding jitpack maven repository to my gradle config files I am not able to use this library, which means that it is only being hosted at jitpack repositories, which are unstable repositories. One option is to publish it to maven central or even github packages.

**Comment by MiSikora** [comment]
And like I mentioned it **is** already on Maven Central - https://search.maven.org/artifact/com.github.chuckerteam.chucker/library.
