### ISSUE TITLE
Allow API response replacement

### ISSUE THREAD

**Issue by samdroidpiercy** [ChuckerTeam/chucker#903]
## :warning: Is your feature request related to a problem? Please describe

Chucker is a fantastic tool for viewing the app's API calls and much like Charles in this way. However, there is feature on Charles that is really useful when debugging applications- that is the ability to replace every call to specific endpoint with a custom response body and/or result code. This is useful, because it allows QAs to test cases that are not necessarily easy to replicate. These could be time-based responses (having to make the request at 10pm in the evening), internal error responses, rare response cases and testing the App's response to any new endpoint that hasn't been setup yet but we know what the response will look like. 

## :bulb: Describe the solution you'd like

As a Developer or QA I want to be able to be able to replace the response body and response code of a previous request so that from that point onwards I get a set response returned from that endpoint.
Example of how it works: 
Click the edit button next to the request (doesn't have to be so huge)
<img width="369" alt="Screenshot 2022-10-04 at 17 01 24" src="https://user-images.githubusercontent.com/84770694/193869707-d158be32-dd9b-45e3-ac68-9f916def8136.png">

This shows you the response body and response code that was returned for this request:

<img width="391" alt="Screenshot 2022-10-04 at 17 01 34" src="https://user-images.githubusercontent.com/84770694/193869902-436d9428-bf83-4236-9974-949254e57e19.png">

You can edit the request body or response code for the next response. In this case I have changed the time of the first item to 1000000. Then clicked ADD MOCK RESPONSE

<img width="383" alt="Screenshot 2022-10-04 at 17 10 19" src="https://user-images.githubusercontent.com/84770694/193870652-d0a1230c-493a-4f87-838c-f9b766910a47.png">

We then do an action in the app that will trigger this request again and see it in chucker highlighted in green (can edit the colour of this) to show that it is a mocked response. 

<img width="376" alt="Screenshot 2022-10-04 at 17 02 45" src="https://user-images.githubusercontent.com/84770694/193871007-6be517c5-5284-4c4d-96ae-a717b1e48274.png">

You can see that the response has come back with the 1000000 time that we wanted.

<img width="375" alt="Screenshot 2022-10-04 at 17 05 30" src="https://user-images.githubusercontent.com/84770694/193871151-03d55be6-0564-408d-ae7a-57257e143045.png">

Like I said- this is very rough at the moment, the edit view is not even formatted nicely. My main question is asked in the "Additional context" section.

## :bar_chart: Describe alternatives you've considered

I can also add my own implementation to the debug drawer, but an integration with chucker is much more preferable, as you can simply edit a request you already have and also see which requests have been edited.

## :page_facing_up: Additional context

I have already produced a very rough version of this, which works relatively well but is not fully developed yet and needs to be refactored. My concern is that I am on version 3.5.2 and on another PR you said there may be some structural changes to the project.  I am trying to ascertain whether it is worth me putting together a polished PR for this, whether you want this and ultimately whether it will be accepted. Also any suggestions for polishing would be well received.

Full disclosure- to achieve this I edited the ChuckerInterceptor, the TransactionAdapter (obviously) and updated the DB. 

## :raising_hand: Do you want to develop this feature yourself?

- [x] Yes 
- [ ] No

**Comment by vbuberen** [comment]
Thanks for the idea.

I don't think this feature should be added into Chucker. Chucker is a simple network monitoring tool, not a fully fledged toolbox to manipulate data for the app where Chucker is used. 

I would suggest you to create a separate library for such purposes instead, because the idea sound good for some applications and might be useful for somebody else.

**Comment by cortinico** [comment]
Agree with @vbuberen 
This change will be really invasive to both the UI and our internals.

As you also mentioned @samdroidpiercy, I'm currently working on #259 (it's going to take some time though as the change is quite extensive). I'm looking into using immutability as much as possible, therefore changing request/response bodies doesn't really play well here.

Moreover, we'll have to retain both the original and the returned body (as the user needs to know if a rewriting happend). On top of that, we'll have to handle the Regex matching to decide when a rewriting should happen. That's definitely non trivial.

It seems like this is something you can achieve with a custom OkHTTP before/after Chucker.
