### ISSUE TITLE
Provide a way to query / get logs

### ISSUE THREAD

**Issue by jagl16** [ChuckerTeam/chucker#91]
**Is your feature request related to a problem? Please describe.**
In Chuck the only way to get a log of the requests was through reflection for the Db open helper.
It would be very useful to add a way to obtain the records to export a trace

**Describe the solution you'd like**
Add to Chucker a method to query the logs and get a list of http or error logs.

**Comment by kylefowler** [comment]
Super useful for using Chucker as a part of an internal build suite where you want to attach network logs to a debug output in a ticket.
