### ISSUE TITLE
Request body is not searchable

### ISSUE THREAD

**Issue by Pitel** [ChuckerTeam/chucker#92]
**Describe the bug**
I can search in response, but not in request body.

**To Reproduce**
1. Go to any request tab
2. Magnifying class icon is missing

**Expected behavior**
There is a working magnifying class icon for searching in request body, same as in response tab.

**Smartphone**
 - Device: Nexus 5X
 - OS: LineageOS 15.1 (8.1)
 - Lib version: 3.0.0

**Comment by cortinico** [comment]
Sounds like a reasonable feature to add :)

**Comment by cortinico** [comment]
Closed by #98
