### ISSUE TITLE
Not working on android 13, Api level 33

### ISSUE THREAD

**Issue by ibrahim-sdsol** [ChuckerTeam/chucker#926]

**Comment by KarimFikani** [comment]
yep facing the same issue

**Comment by vbuberen** [comment]
There is no description provided about what exactly not working.

Use SNAPSHOT version of Chucker - it has support of Android 13.
https://github.com/ChuckerTeam/chucker#snapshots-

**Comment by KarimFikani** [comment]
@vbuberen I tried 4.0-snapshot and still chucker does not work. I have Cucker setup as an interceptor and previously I would get a notification when that specific API is getting called and I get all the data but now not anymore. Started happening with android 13.

**Comment by vbuberen** [comment]
You need to provide Chucker with notifications permission first. Without it Chucker works, but shows no notification.

To provide such permission use the quick action shortcut which is added to your app when Chucker is added. As soon as you start Chucker this way you would see a permission request. Grant this permission and you will see transactions notifications again.

**Comment by KarimFikani** [comment]
ok works. thx
