### ISSUE TITLE
Stream data via http/adb to attached PC?

### ISSUE THREAD

**Issue by YashKumarVerma** [ChuckerTeam/chucker#932]
## :warning: Is your feature request related to a problem? Please describe
No

## :bulb: Describe the solution you'd like
- ability to see chucker results on the PC
- will make data transfer / inspection / reference easy.

## :bar_chart: Describe alternatives you've considered
- we can send data in a particular format via logcat (not sure if we do this right now, I've mainly worked on backends :/ )
- can start a tiny HTTP server on app that displays the readings and call it a day, system can visit the local IP and get the data

## :page_facing_up: Additional context
- working on product features, its difficult to refer everything in app, I have to repeatedly send myself all the payloads etc as messages to transfer them to my system.

## :raising_hand: Do you want to develop this feature yourself?
- I am new to android ( willing to learn more), so can take this up.

- [x] Yes
- [ ] No

**Comment by vbuberen** [comment]
Thanks for your suggestion. However, I think this feature makes no sense, because Android Studio already has network inspector: https://developer.android.com/studio/debug/network-profiler

**Comment by YashKumarVerma** [comment]
Thanks for your reply, i'm not experienced in the android ecosystem so was not aware of the same.

Does it mandatorily require android studio to be setup in order to use or there's some adb thing going under the hood that cab be done without the dependency ?

**Comment by vbuberen** [comment]
Android Studio is not a dependency, but IDE that you setup on your PC/laptop. You don't need to do any special configs to let it capture network data, but it is a feature of Android Studio. I don't know about under the hood part of that profiler.
