### ISSUE TITLE
Chucker not working on SDK 33 (Android 13)

### ISSUE THREAD

**Issue by liamesnapper** [ChuckerTeam/chucker#934]
## :writing_hand: Describe the bug
When using an Android 13 device (physical or emulated) Chucker doesn't start or at least doesn't send any push notifications.

## :bomb: Steps to reproduce

1. Launch an app with Chucker implemented
2. Perform an action that triggers any API call
3. See that no notification from Chucker can be found

## :wrench: Expected behavior
A push notification with the latest HTTP call.

## :iphone: Tech info
Physical:
 - Device: Samsung Galaxy A73
 - OS: Android 13 / One UI 5.0
 - Chucker version: 3.5.2

Emulator:
 - Device: Google Pixel 6 Pro
 - OS: Android 13 / Android Studio SDK 33
 - Chucker version: 3.5.2

## :page_facing_up: Additional context
Running the same app on a device running 12 or below Chucker is behaving as expected.

**Comment by vbuberen** [comment]
Hello there. Our snapshot version supports Android 13. Checkout the README: https://github.com/ChuckerTeam/chucker#notification-permission-
