### ISSUE TITLE
Image that are too big will make chucker crash

### ISSUE THREAD

**Issue by redwarp** [ChuckerTeam/chucker#94]
**Describe the bug**
Because the image data is stored in database, if an image is too big, it crashes

**To Reproduce**
1. Use Chucker to download a really big image, like https://i.ibb.co/znbM2dp/IMG-20190812-194359.jpg

**Expected behavior**
Chucker should work

**Comment by cortinico** [comment]
That's a bug.
Apparently we can't store more than 1Mb of data as blob in the sqlite db.

Ideally we should either:

* Do not store images that are bigger than 1Mb
* Downscale images to store just a thumbnail
* Store images on the external storage and have the URI stored inside the DB

I'm open for suggestions/ideas here

**Comment by redwarp** [comment]
I think we should do a quick fix and simply drop the image if bigger than 1MB, and release 3.0.1
And then, improve on it.

- Downscale images seems like a good idea, expect it will means that chucker will start to use more resources to process that. It might be okay if we run this on a low prio thread I guess.
- Store images or simply blob of binary file, but it brings its own crazies: if an app download 10 images of 10 megs, then chucker will use 100 megs of space. Plus we will have to make sure that we clean things properly.

**Comment by cortinico** [comment]
Given that this was considered a regression, I just published an hotfix with this fix:
https://github.com/ChuckerTeam/chucker/releases/tag/3.0.1
