### ISSUE TITLE
Version 3.5.3 and Log List Access

### ISSUE THREAD

**Issue by amertaslan** [ChuckerTeam/chucker#953]
When will version 3.5.3 be released?
I want to access the log list. How can i get chucker http logs? Is there a way to do this?

**Comment by vbuberen** [comment]
It is 4.0 release that is going to be next. For now there is no timeline for it.

As to log list - you need to explain better what exactly you want. You can already export transactions to file from released version. If you need support of export in `har` format you can use SNAPSHOT build: https://github.com/ChuckerTeam/chucker#snapshots-
