### ISSUE TITLE
Doesn't work / shown on Samsung A23 with One UI version 5.0, Android 13

### ISSUE THREAD

**Issue by i01107** [ChuckerTeam/chucker#965]
## :writing_hand: Describe the bug
I have a Samsung A23 with One UI version 5.0, Android 13 currently. Previously, before it asked for update, chucker went find and it shown as expected

## :bomb: Steps to reproduce
Just try to use Samsung A23 with its latest OS and run any app from app tester or just a wild APK with chucker installed

## :wrench: Expected behavior
Expecting to see the chucker windows

## :iphone: Tech info
 - Device: Samsung A23
 - OS: Android 13
 - Chucker version:

**Comment by vbuberen** [comment]
Android 13 requires notification permission. Chucker supports Android 13 notification permissions only in snapshot builds at the moment.

You can find information about both notifications permission and snapshot builds in the README file.

https://github.com/ChuckerTeam/chucker#notification-permission-
