### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by gitkobold** [ChuckerTeam/chucker#971]
Hi,

I can see some commits and 47 contributors but there isn't any release since almost two years and the pull requests are also pending too long.
What is status of this project?
Thanks a lot

**Comment by cortinico** [comment]
> What is status of this project?

The project is active. I'm working on it on my spare time (which sadly is really limited).
We recently onboarded @ArjanSM to the ChuckerTeam which will help us with the workload.

As for a new release, I know we're long overdue.
I've been personally working on a major rework of the internals that is taking more than anticipated, so we'll release 4.x when we're ready :)

Any help is also more than welcome 🙏
