### ISSUE TITLE
releaseImplementation is not working on multi module project

### ISSUE THREAD

**Issue by wellyogui** [ChuckerTeam/chucker#981]
## :writing_hand: Describe the bug
My project is a multi module app, I have a module for the service layer that I implemented the Chucker and when I build for my project in release mode the Chucker still visible.

Here is my base service gradle, is really simple.

     apply plugin: 'com.android.library'
     apply plugin: 'kotlin-android'
     apply plugin: 'kotlin-android-extensions'

    android {
     compileSdkVersion rootProject.ext.compileVersion
     buildToolsVersion = rootProject.ext.buildToolsVersion

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.1"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    }
 
    dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // Kotlin
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    //Retrofit
    api "com.squareup.okhttp3:logging-interceptor:${rootProject.ext.loggingInterceptor}"
    api "com.squareup.retrofit2:retrofit:${rootProject.ext.retrofitVersion}"
    api "com.squareup.retrofit2:adapter-rxjava2:${rootProject.ext.retrofitVersion}"
    api "com.squareup.retrofit2:converter-gson:${rootProject.ext.retrofitVersion}"

    //Timber
    api "com.jakewharton.timber:timber:$rootProject.ext.timberVersion"

    //Timezone
    api "com.jakewharton.threetenabp:threetenabp:$rootProject.ext.threetenabp"

    //RX
    api "io.reactivex.rxjava2:rxjava:${rootProject.ext.rxJavaVersion}"
    api "io.reactivex.rxjava2:rxandroid:${rootProject.ext.rxAndroidVersion}"

    debugImplementation "com.github.chuckerteam.chucker:library:3.5.2"
    releaseImplementation "com.github.chuckerteam.chucker:library-no-op:3.5.2"
    }`

 The signingConfigs and buildTypes is on the app module. Should I create a signgConfigs and buildTypes on this base service gradle too?

## :bomb: Steps to reproduce

1. Create a new module for service and implement chucker on this module
2. Generate signed apk 
3. Verify if Chucker is still visible

## :wrench: Expected behavior
Not showing Chucker on signed apk.

## :iphone: Tech info
 - Device: Samsung S10+
 - OS: Android 12
 - Chucker version: 3.5.2

**Comment by cortinico** [comment]
> 1. Create a new module for service and implement chucker on this module

Can you create a reproducer? (you can use this template github.com/cortinico/kotlin-android-template/).

You setup seems correct so I'm not sure what's going on

**Comment by jaeryo2357** [comment]
@wellyogui  Hi, my project is multi module app, but chucker is disable in release mode
I think you should replace it like this.

``` diff
- debugImplementation "com.github.chuckerteam.chucker:library:3.5.2"
- releaseImplementation "com.github.chuckerteam.chucker:library-no-op:3.5.2"
+ debugApi "com.github.chuckerteam.chucker:library:3.5.2"
+ releaseApi "com.github.chuckerteam.chucker:library-no-op:3.5.2"
```

**Comment by wellyogui** [comment]
@jaeryo2357 with `BuildConfig.DEBUG` worked for me. Thanks!
