### ISSUE TITLE
merge debug resources failed android studio

### ISSUE THREAD

**Issue by Gnanendra18** [ChuckerTeam/chucker#991]
## :writing_hand: Compile issues in Android compile sdk version 33
The code is not building due to merging of resource files getting failed.

## :bomb: Steps to reproduce

1. Change compile sdk version of client app to 33 
2. Change target sdk version of client app to 33
3. build the code 

## :camera: Screenshots

![image](https://user-images.githubusercontent.com/5127272/228214552-000c5849-26fb-4e70-8a07-cb7fc4a13db4.png)

## :iphone: Tech info
 - Device: Xiomi mi A3 or any other android device
 - OS: Android 12 
 - Chucker version: 3.5.2

**Comment by Gnanendra18** [comment]
This issue is causing due to read me string in the code please remove this line in strings.xml in values folder
 <string name="chucker_check_readme"><a href="https://github.com/ChuckerTeam/chucker/blob/develop/README.md#configure-">Check the setup instructions on GitHub</a></string>

**Comment by cortinico** [comment]
Please check my comment on:
- https://github.com/ChuckerTeam/chucker/pull/992
